In [7]:
lista = [1,2,3,4,5,6,7]
lista2 = ["Save","The","Pandas"]

In [3]:
lista3 = enumerate(lista)
lista3

In [5]:
for element in enumerate(lista):
    print element

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)


In [14]:
for element in lista2:
    print element

Save
The
Pandas


In [17]:
len(lista2)

3

In [18]:
for number in lista:
    print 2*number+1

3
5
7
9
11
13
15


In [102]:
lista3=[number*2+1.5 for number in range(1,4)]
lista3

[3.5, 5.5, 7.5]

In [105]:
lista3=[number*2+1 for number in lista]
lista3

[3, 5, 7, 9, 11, 13, 15]

In [34]:
dic={"Nombre":'Javier',"Apellido":'Almendro',"Edad":48}

In [35]:
dic

{'Apellido': 'Almendro', 'Edad': 48, 'Nombre': 'Javier'}

In [44]:
for element in dic:
    print element

Edad
Nombre
Apellido


In [55]:
for element in dic:
    print element,dic[element]
    

Edad 48
Nombre Javier
Apellido Almendro


In [3]:
import numpy as np

In [58]:
array1=np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [66]:
%time newlist=[number+1 for number in range(0,100000)]
newlist[:10]

CPU times: user 13.5 ms, sys: 234 µs, total: 13.7 ms
Wall time: 13.8 ms


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [67]:
%time newarray=np.arange(100000)+1
newarray[:10]

CPU times: user 244 µs, sys: 1.32 ms, total: 1.56 ms
Wall time: 1.6 ms


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
import pandas as pd
from pandas import Series

In [8]:
serie1 = Series(lista2)
serie1

0      Save
1       The
2    Pandas
dtype: object

In [96]:
serie1.index.values

array([0, 1, 2])

In [97]:
serie1.values

array(['Save', 'The', 'Pandas'], dtype=object)

In [99]:
serie2 = Series(lista2,index=['e1','e2','e3'])
serie2

e1      Save
e2       The
e3    Pandas
dtype: object

In [100]:
serie2.index.values

array(['e1', 'e2', 'e3'], dtype=object)

In [107]:
serie3 = Series(lista3)
serie3

0     3
1     5
2     7
3     9
4    11
5    13
6    15
dtype: int64

In [108]:
serie3+serie3

0     6
1    10
2    14
3    18
4    22
5    26
6    30
dtype: int64

In [110]:
serie3*2.5

0     7.5
1    12.5
2    17.5
3    22.5
4    27.5
5    32.5
6    37.5
dtype: float64

In [120]:
serie4 = Series(lista3,index=[0,1,2,3,4,5,7])
serie4+serie3*10000

0     30003
1     50005
2     70007
3     90009
4    110011
5    130013
6       NaN
7       NaN
dtype: float64

In [113]:
serie3+serie4

0   NaN
1     8
2    12
3    16
4    20
5    24
6    28
7   NaN
dtype: float64

In [121]:
from pandas import DataFrame

In [123]:
df1 = DataFrame([serie3,serie4])
df1

0  1  2  3   4   5   6   7
0  3  5  7  9  11  13  15 NaN
1  3  5  7  9  11  13 NaN  15

In [124]:
serie4=2*serie3
df1 = DataFrame([serie3,serie4])
df1

0   1   2   3   4   5   6
0  3   5   7   9  11  13  15
1  6  10  14  18  22  26  30

In [137]:
df1[0]

0    3
1    6
Name: 0, dtype: int64

In [127]:
df1.index.values

array([0, 1])

In [130]:
df1.columns.values

array([0, 1, 2, 3, 4, 5, 6])

In [142]:
df1=DataFrame({"col1":serie3,"col2":serie4})
df1

col1  col2
0     3     6
1     5    10
2     7    14
3     9    18
4    11    22
5    13    26
6    15    30

In [144]:
df1["col3"]=1
df1

col1  col2  col3
0     3     6     1
1     5    10     1
2     7    14     1
3     9    18     1
4    11    22     1
5    13    26     1
6    15    30     1

In [147]:
df1['col4']=np.arange(len(lista))
df1

col1  col2  col3  col4
0     3     6     1     0
1     5    10     1     1
2     7    14     1     2
3     9    18     1     3
4    11    22     1     4
5    13    26     1     5
6    15    30     1     6

In [150]:
df1['col4'][4]

4

In [152]:
df1['col4'].index.values

array([0, 1, 2, 3, 4, 5, 6])

In [154]:
df1['col2'].values

array([ 6, 10, 14, 18, 22, 26, 30])

In [1]:
%time lista9=[number+1 for number in range(0,10000)]
lista9[:10]

CPU times: user 1.54 ms, sys: 0 ns, total: 1.54 ms
Wall time: 1.57 ms


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
%time array9=np.arange(10000)+1
array9[:10]

CPU times: user 82 µs, sys: 31 µs, total: 113 µs
Wall time: 117 µs


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
serie9=Series(lista2)

In [10]:
serie9

0      Save
1       The
2    Pandas
dtype: object

In [11]:
serie9.index.values

array([0, 1, 2])

In [12]:
serie9.values

array(['Save', 'The', 'Pandas'], dtype=object)

In [13]:
list9=lista9

In [14]:
list8=["Kill","The","Snakes"]

In [15]:
list8

['Kill', 'The', 'Snakes']

In [16]:
serie8=Series(list8)
serie8

0      Kill
1       The
2    Snakes
dtype: object

In [19]:
serie8=Series(list8,index=['Sujeto','Verbo','Predicado'])
serie8

Sujeto         Kill
Verbo           The
Predicado    Snakes
dtype: object

In [22]:
serie9=Series(lista2,index=['Sujeto','Verbo','Predicado'])
serie9

Sujeto         Save
Verbo           The
Predicado    Pandas
dtype: object

In [23]:
serie9['Sujeto']

'Save'

In [35]:
array9=(np.arange(9)+1)*3.141592
array8=np.arange(9)
serie9=Series(array8)
serie98=Series(array9,index=array8)
serie98

0     3.141592
1     6.283184
2     9.424776
3    12.566368
4    15.707960
5    18.849552
6    21.991144
7    25.132736
8    28.274328
dtype: float64

In [39]:
array9=(np.arange(7)+1)*3.141592
serie9=Series(array9)
serie9+serie98

0     6.283184
1    12.566368
2    18.849552
3    25.132736
4    31.415920
5    37.699104
6    43.982288
7          NaN
8          NaN
dtype: float64

In [42]:
array9=(np.arange(7)+1)
serie9=Series(array9)

In [55]:
serie9
serie1=serie9
serie1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [57]:
serie2=serie1*2
from pandas import DataFrame
df1=DataFrame([serie1,serie2])
df1

0  1  2  3   4   5   6
0  1  2  3  4   5   6   7
1  2  4  6  8  10  12  14

In [269]:
df1=DataFrame({'col1':serie1,'col2':serie2})
df1

col1  col2
0     1     2
1     2     4
2     3     6
3   NaN     8
4     5    10
5     6    12
6     7    14

In [270]:
df1['col3']=1
df1

col1  col2  col3
0     1     2     1
1     2     4     1
2     3     6     1
3   NaN     8     1
4     5    10     1
5     6    12     1
6     7    14     1

In [65]:
df1['col2'].values

array([ 2,  4,  6,  8, 10, 12, 14])

In [271]:
df1['col4']=Series(np.arange(7))
df1

col1  col2  col3  col4
0     1     2     1     0
1     2     4     1     1
2     3     6     1     2
3   NaN     8     1     3
4     5    10     1     4
5     6    12     1     5
6     7    14     1     6

In [75]:
df1['col4'][3]=np.nan
df1

/usr/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


col1  col2  col3  col4
0     1     2     1     0
1     2     4     1     1
2     3     6     1     2
3   NaN   NaN   NaN   NaN
4     5    10     1     4
5     6    12     1     5
6     7    14     1     6

In [274]:
df1

col1  col2  col3  col4
0     1     2     1     0
1     2     4     1     1
2     3     6     1     2
3   NaN     8     1     3
4     5    10     1     4
5     6    12     1     5
6     7    14     1     6

In [276]:
df1.dropna()


col1  col2  col3  col4
0     1     2     1     0
1     2     4     1     1
2     3     6     1     2
4     5    10     1     4
5     6    12     1     5
6     7    14     1     6

In [80]:
serie1=df1['col1']
serie1

0     1
1     2
2     3
3   NaN
4     5
5     6
6     7
Name: col1, dtype: float64

In [81]:
serie1.dropna()

0    1
1    2
2    3
4    5
5    6
6    7
Name: col1, dtype: float64

In [83]:
df1.T.index.values

array(['col1', 'col2', 'col3', 'col4'], dtype=object)

In [84]:
df1.values

array([[  1.,   2.,   1.,   0.],
       [  2.,   4.,   1.,   1.],
       [  3.,   6.,   1.,   2.],
       [ nan,  nan,  nan,  nan],
       [  5.,  10.,   1.,   4.],
       [  6.,  12.,   1.,   5.],
       [  7.,  14.,   1.,   6.]])

In [94]:
df1['col2'][1]

4.0

In [105]:
df1[df1.columns]

col1  col2  col3  col4
0     1     2     1     0
1     2     4     1     1
2     3     6     1     2
3   NaN   NaN   NaN   NaN
4     5    10     1     4
5     6    12     1     5
6     7    14     1     6

In [113]:
df1=df1.dropna()

In [114]:
df1.columns.values

array(['col1', 'col2', 'col3', 'col4'], dtype=object)

In [115]:
df1.index.values

array([0, 1, 2, 4, 5, 6])

In [120]:
df1.values[:][2:]

array([[  3.,   6.,   1.,   2.],
       [  5.,  10.,   1.,   4.],
       [  6.,  12.,   1.,   5.],
       [  7.,  14.,   1.,   6.]])

In [121]:
index1=df1.index

In [123]:
20 in index1

False

In [124]:
index2=df1.columns

In [125]:
'col2' in index2

True

In [126]:
df1+2*df1

col1  col2  col3  col4
0     3     6     3     0
1     6    12     3     3
2     9    18     3     6
4    15    30     3    12
5    18    36     3    15
6    21    42     3    18

In [127]:
df1.columns=['c1','c2','c3','c4']

In [177]:
df1.reindex(columns=['c1','c2','c4'])


c1  c2  c4
0   1   2   0
1   2   4   1
2   3   6   2
4   5  10   4
5   6  12   5
6   7  14   6

In [178]:
df1

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [134]:
pd.concat(df1,df1)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [162]:
df2=[df1,df1]
df2

[   c1  c2  c3  c4
 0   1   2   1   0
 1   2   4   1   1
 2   3   6   1   2
 4   5  10   1   4
 5   6  12   1   5
 6   7  14   1   6,    c1  c2  c3  c4
 0   1   2   1   0
 1   2   4   1   1
 2   3   6   1   2
 4   5  10   1   4
 5   6  12   1   5
 6   7  14   1   6]

In [163]:
df2=df1

In [164]:
df2.columns=['c1','c2','c3','c4']

In [165]:
df2

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [166]:
df1

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [167]:
df2=df1.copy()

In [168]:
df2

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [284]:
df1.columns=['c1','c2','c3','c5']
df2

c1  c2  c3  c5
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [170]:
df1

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [171]:
[df1,df2]

[   c1  c2  c3  c4
 0   1   2   1   0
 1   2   4   1   1
 2   3   6   1   2
 4   5  10   1   4
 5   6  12   1   5
 6   7  14   1   6,    c1  c2  c3  c5
 0   1   2   1   0
 1   2   4   1   1
 2   3   6   1   2
 4   5  10   1   4
 5   6  12   1   5
 6   7  14   1   6]

In [174]:
df3=pd.concat([df1,df2])
df3['c4']=1

In [175]:
df3.dropna()

c1  c2  c3  c4  c5
0   1   2   1   1   0
1   2   4   1   1   1
2   3   6   1   1   2
4   5  10   1   1   4
5   6  12   1   1   5
6   7  14   1   1   6

In [176]:
df3

c1  c2  c3  c4  c5
0   1   2   1   1 NaN
1   2   4   1   1 NaN
2   3   6   1   1 NaN
4   5  10   1   1 NaN
5   6  12   1   1 NaN
6   7  14   1   1 NaN
0   1   2   1   1   0
1   2   4   1   1   1
2   3   6   1   1   2
4   5  10   1   1   4
5   6  12   1   1   5
6   7  14   1   1   6

In [180]:
df3

c1  c2  c3  c4  c5
0   1   2   1   1 NaN
1   2   4   1   1 NaN
2   3   6   1   1 NaN
4   5  10   1   1 NaN
5   6  12   1   1 NaN
6   7  14   1   1 NaN
0   1   2   1   1   0
1   2   4   1   1   1
2   3   6   1   1   2
4   5  10   1   1   4
5   6  12   1   1   5
6   7  14   1   1   6

In [181]:
df3.fillna(3)

c1  c2  c3  c4  c5
0   1   2   1   1   3
1   2   4   1   1   3
2   3   6   1   1   3
4   5  10   1   1   3
5   6  12   1   1   3
6   7  14   1   1   3
0   1   2   1   1   0
1   2   4   1   1   1
2   3   6   1   1   2
4   5  10   1   1   4
5   6  12   1   1   5
6   7  14   1   1   6

In [182]:
df3

c1  c2  c3  c4  c5
0   1   2   1   1 NaN
1   2   4   1   1 NaN
2   3   6   1   1 NaN
4   5  10   1   1 NaN
5   6  12   1   1 NaN
6   7  14   1   1 NaN
0   1   2   1   1   0
1   2   4   1   1   1
2   3   6   1   1   2
4   5  10   1   1   4
5   6  12   1   1   5
6   7  14   1   1   6

In [183]:
df1

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [188]:
df1.ix[0].index

Index([u'c1', u'c2', u'c3', u'c4'], dtype='object')

In [191]:
df1['c1']>3

0    False
1    False
2    False
4     True
5     True
6     True
Name: c1, dtype: bool

In [194]:
array9>3

array([False, False, False,  True,  True,  True,  True], dtype=bool)

In [196]:
df1.index>3

array([False, False, False,  True,  True,  True], dtype=bool)

In [204]:
df1

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [203]:
df1[df1['c1']>3]

c1  c2  c3  c4
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [213]:
df1[[True,True,False,True,False,True]]

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
4   5  10   1   4
6   7  14   1   6

In [214]:
df1

c1  c2  c3  c4
0   1   2   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6  12   1   5
6   7  14   1   6

In [219]:
df1[(df1['c1']>3) & (df1['c2']<13)]

c1  c2  c3  c4
4   5  10   1   4
5   6  12   1   5

In [220]:
def suma(val):
    return val+1

In [221]:
suma(5)

6

In [222]:
suma(df1['c2'])

0     3
1     5
2     7
4    11
5    13
6    15
Name: c2, dtype: float64

In [226]:
suma(df1)

c1  c2  c3  c4
0   2   3   2   1
1   3   5   2   2
2   4   7   2   3
4   6  11   2   5
5   7  13   2   6
6   8  15   2   7

In [230]:
def cuadrado(val):
    return val*2;

In [228]:
cuadrado(df1)

c1   c2  c3  c4
0   1    4   1   0
1   4   16   1   1
2   9   36   1   4
4  25  100   1  16
5  36  144   1  25
6  49  196   1  36

In [231]:
df1.applymap(cuadrado)

c1  c2  c3  c4
0   2   4   2   0
1   4   8   2   2
2   6  12   2   4
4  10  20   2   8
5  12  24   2  10
6  14  28   2  12

In [286]:
df1.applymap(lambda element : element*2)

c1  c2  c3  c5
0   2   4   2   0
1   4   8   2   2
2   6  12   2   4
4  10  20   2   8
5  12  24   2  10
6  14  28   2  12

In [292]:
df1['c2'][0]=20
df1

/usr/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


c1  c2  c3  c5
0   1  20   1   0
1   2   4   1   1
2   3   6   1   2
4   5  10   1   4
5   6   0   1   5
6   7  14   1   6

In [313]:
df1.apply(lambda serie : Series([serie[5],serie[4]]))

c1  c2  c3  c5
0   6   0   1   5
1   5  10   1   4

In [305]:
seriedatoscol1=Series([df1['c1'].max(),df1['c1'].mean(),df1['c1'].min()])

In [307]:
df1.apply(lambda serie : serie.min())

c1    1
c2    0
c3    1
c5    0
dtype: float64

In [282]:
df1=df1.dropna()
df1.

col1  col2  col3  col4
0     1     2     1     0
1     2     4     1     1
2     3     6     1     2
4     5    10     1     4
5     6    12     1     5
6     7    14     1     6

In [245]:
def minserie(serie):
    return serie.min()
minserie(df1["c2"])

2.0

In [246]:
df1.apply(minserie)

c1    1
c2    2
c3    1
c4    0
dtype: float64

In [249]:
df1.apply(lambda serie : Series([serie.min(),serie.max()]))

c1  c2  c3  c4
0   1   2   1   0
1   7  14   1   6

In [254]:
df1['c1'].mean()

4.0

In [1]:
import pandas as pd
from pandas import Series,DataFrame

In [2]:
aircraftdf = pd.read_csv("/home/dsc/Data/opentraveldata/optd_aircraft.csv")


In [3]:
aircraftdf.ix(0)

In [5]:
aircraftdf.columns.values

array([ 'iata_code^manufacturer^model^iata_group^iata_category^icao_code^nb_engines^aircraft_type'], dtype=object)

In [6]:
aircraftdf = pd.read_csv("/home/dsc/Data/opentraveldata/optd_aircraft.csv",sep="^")


In [7]:
aircraftdf.head()

iata_code manufacturer                          model iata_group  \
0       100       Fokker                            100        100   
1       141          BAe                        146-100        146   
2       142          BAe  BAE Systems 146-200 Passenger        146   
3       143          BAe                        146-300        146   
4       146          BAe                            146        NaN   

  iata_category icao_code  nb_engines aircraft_type  
0            2J      F100           2             J  
1            4J      B461           4             J  
2            4J      B462           4             J  
3            4J      B463           4             J  
4           NaN       NaN         NaN           NaN

In [14]:
aircraftdf[aircraftdf['nb_engines'] > 2]['nb_engines'].sum()

331.0

In [17]:
len(aircraftdf)-len(aircraftdf.dropna())

116

In [18]:
aircraftdf.describe()

nb_engines
count  343.000000
mean     2.408163
std      0.842679
min      1.000000
25%      2.000000
50%      2.000000
75%      3.000000
max      6.000000

In [19]:
aircraftdf['iata_code'].head()

0    100
1    141
2    142
3    143
4    146
Name: iata_code, dtype: object

In [20]:
aircraftdf.describe()

nb_engines
count  343.000000
mean     2.408163
std      0.842679
min      1.000000
25%      2.000000
50%      2.000000
75%      3.000000
max      6.000000

In [22]:
aircraftdf.sort('nb_engines',ascending=False).head()

iata_code manufacturer            model iata_group iata_category  \
145       A5F      Antonov           An-225        A5F            6J   
89        742       Boeing          747-200        747            4J   
106       74V       Boeing  747SR Freighter        74F            4J   
94        74C       Boeing    747-200 Combi        74M            4J   
368       IL8     Ilyushin            IL-18        IL8            4T   

    icao_code  nb_engines aircraft_type  
145      A225           6             J  
89       B742           4             J  
106      B74R           4             J  
94       B742           4             J  
368      IL18           4             T

In [1]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

In [2]:
aircraftdf = pd.read_csv("/home/dsc/Data/opentraveldata/optd_aircraft.csv",sep="^")

In [5]:
aircraftdf.sort("nb_engines",ascending=False).head()

iata_code manufacturer            model iata_group iata_category  \
145       A5F      Antonov           An-225        A5F            6J   
89        742       Boeing          747-200        747            4J   
106       74V       Boeing  747SR Freighter        74F            4J   
94        74C       Boeing    747-200 Combi        74M            4J   
368       IL8     Ilyushin            IL-18        IL8            4T   

    icao_code  nb_engines aircraft_type  
145      A225           6             J  
89       B742           4             J  
106      B74R           4             J  
94       B742           4             J  
368      IL18           4             T

In [10]:
aircraftdf.reindex(columns=['iata_code','manufacturer','nb_engines']).to_excel("hola.xls")fileo

In [11]:
fileout = open('prueba.txt','w')

In [16]:
fileout.write(aircraftdf['nb_engines'].head(2).to_dict())

TypeError: expected a character buffer object

In [24]:
fileout.write(aircraftdf.head().to_json(orient="records"))

In [25]:
fileout.close()

In [44]:
df2=DataFrame(np.random.randn(1000,1))
df2.head()

0
0  1.060313
1  1.071316
2 -0.242880
3 -0.023504
4 -0.250969

In [46]:
df2.columns=['Population']
DataFrame(df2.apply(lambda row: int(abs(row*10000)),axis=1))

0
0    10603
1    10713
2     2428
3      235
4     2509
5    14697
6     5295
7    12447
8     9509
9     9485
10    3089
11    8180
12    2058
13     950
14    4833
15    2437
16    7515
17    4999
18    2175
19    9092
20    3809
21    3379
22     805
23    4487
24    8430
25     891
26    9064
27   14112
28    8288
29    5358
..     ...
970  10122
971  11191
972   8444
973   9653
974   3865
975    864
976   9661
977   4773
978    895
979  18802
980  11859
981    802
982  17741
983   4617
984  22427
985   7563
986  10982
987  12848
988  10012
989  15777
990  20080
991  11735
992   2544
993  13708
994   1119
995  16816
996    590
997   2228
998   1479
999  13212

[1000 rows x 1 columns]

In [47]:
df2.count()

Population    1000
dtype: int64

In [48]:
aircraftdf.count()

iata_code        457
manufacturer     453
model            457
iata_group       363
iata_category    363
icao_code        363
nb_engines       343
aircraft_type    362
dtype: int64

In [49]:
aircraftdf.sum()

nb_engines    826
dtype: float64

In [51]:
aircraftdf['aircraft_type'].dropna().unique()

array(['J', 'T', 'P', 'H', 'S'], dtype=object)

In [60]:
aircraftdf.groupby('aircraft_type').count()


iata_code  manufacturer  model  iata_group  iata_category  \
aircraft_type                                                              
H                     12            12     12          12             12   
J                    231           230    231         231            231   
P                     30            30     30          30             30   
S                      6             4      6           6              6   
T                     83            82     83          83             83   

               icao_code  nb_engines  
aircraft_type                         
H                     12           0  
J                    231         231  
P                     30          30  
S                      6           0  
T                     83          82

In [61]:
cadena = """Abkhazia
Afghanistan
Akrotiri and Dhekelia
Aland
Albania
Algeria
American Samoa
Andorra
Angola
Anguilla
Antigua and Barbuda
Argentina
Armenia
Aruba
Ascension Island
Australia
Austria
Azerbaijan
Bahamas, The
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bermuda
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burundi
Cambodia
Cameroon
Canada
Cape Verde
Cayman Islands
Central Africa Republic
Chad
Chile
China
Christmas Island
Cocos (Keeling) Islands
Colombia
Comoros
Congo
Cook Islands
Costa Rica
Cote d'lvoire
Croatia
Cuba
Cyprus
Czech Republic
Denmark
Djibouti
Dominica
Dominican Republic
East Timor Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Ethiopia
Falkland Islands
Faroe Islands
Fiji
Finland
France
French Polynesia
Gabon
Cambia, The
Georgia
Germany
Ghana
Gibraltar
Greece
Greenland
Grenada
Guam
Guatemala
Guemsey
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hong Kong
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Isle of Man
Israel
Italy
Jamaica
Japan
Jersey
Jordan
Kazakhstan
Kenya
Kiribati
Korea, N
Korea, S
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Macao
Macedonia
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mayotte
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Montserrat
Morocco
Mozambique
Myanmar
Nagorno-Karabakh
Namibia
Nauru
Nepal
Netherlands
Netherlands Antilles
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
Niue
Norfolk Island
Northern Cyprus
Northern Mariana Islands
Norway
Oman
Pakistan
Palau
Palestine
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Pitcaim Islands
Poland
Portugal
Puerto Rico
Qatar
Romania
Russia
Rwanda
Sahrawi Arab Democratic Republic
Saint-Barthelemy
Saint Helena
Saint Kitts and Nevis
Saint Lucia
Saint Martin
Saint Pierre and Miquelon
Saint Vincent and Grenadines
Samos
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
Somaliland
South Africa
South Ossetia
Spain
Sri Lanka
Sudan
Suriname
Svalbard
Swaziland
Sweden
Switzerland
Syria
Tajikistan
Tanzania
Thailand
Togo
Tokelau
Tonga
Transnistria
Trinidad and Tobago
Tristan da Cunha
Tunisia
Turkey
Turkmenistan
Turks and Caicos Islands
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Vatican City
Venezuela
Vietnam
Virgin Islands, British
Virgin Islands, U.S.
Wallis and Futuna
Yemen
Zambia
Zimbabwe"""

In [64]:
countryl=cadena.split("\n")

In [65]:
countryl

['Abkhazia',
 'Afghanistan',
 'Akrotiri and Dhekelia',
 'Aland',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Ascension Island',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas, The',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central Africa Republic',
 'Chad',
 'Chile',
 'China',
 'Christmas Island',
 'Cocos (Keeling) Islands',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 "Cote d'lvoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Falkland 

In [66]:
np.random.randn(2,4)

array([[-0.58915823, -1.49152616,  0.51724525, -0.11869994],
       [-0.084361  , -0.21946812, -1.29291187, -0.30594914]])

In [76]:
np.random.randint(0,242,10)

array([232,  14,  75,  15,   8,  37, 124,   5, 190, 120])

In [71]:
len(countryl)

242

In [81]:
df3=DataFrame({'col1':np.random.randint(0,242,10)})

In [82]:
df3

col1
0    17
1   220
2   174
3   173
4    55
5   195
6   214
7   193
8    30
9    19

In [85]:
df3['col2']=df3.apply(lambda row : countryl[row['col1']],axis=1)
df3

col1          col2
0    17    Azerbaijan
1   220       Tunisia
2   174         Qatar
3   173   Puerto Rico
4    55        Cyprus
5   195      Slovakia
6   214          Togo
7   193  Sierra Leone
8    30      Botswana
9    19       Bahrain

In [103]:
%matplotlib inline
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib
import matplotlib.pyplot as plt

In [104]:
plt.title('Mi primera grafica')
plt.xlabel('indice')
plt.ylabel('valores')
plt.plot(x ,y, label="Linea1")

plt.legend(loc='best',frameon=False)

TypeError: 'str' object is not callable

In [99]:
plt.title("jalmen")
plt.pie(Series(x))


TypeError: 'str' object is not callable

In [109]:
df=pd.read_csv("/tmp/On_Time_On_Time_Performance_2015_1.csv",low_memory=False)

In [110]:
df.sample(5)

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
215759  2015        1      1          27          2  2015-01-27            WN   
325019  2015        1      1           4          7  2015-01-04            UA   
176064  2015        1      1          30          5  2015-01-30            US   
264848  2015        1      1          18          7  2015-01-18            OO   
361698  2015        1      1          25          7  2015-01-25            DL   

        AirlineID Carrier TailNum      ...       Div4TailNum  Div5Airport  \
215759      19393      WN  N403WN      ...               NaN          NaN   
325019      19977      UA  N846UA      ...               NaN          NaN   
176064      20355      US  N553UW      ...               NaN          NaN   
264848      20304      OO  N631SK      ...               NaN          NaN   
361698      19790      DL  N956DN      ...               NaN          NaN   

        Div5AirportID  Div5AirportSeqID Div5WheelsOn Div5TotalGTime  \
215759            NaN               NaN          NaN            NaN   
325019            NaN               NaN          NaN            NaN   
176064            NaN               NaN          NaN            NaN   
264848            NaN               NaN          NaN            NaN   
361698            NaN               NaN          NaN            NaN   

       Div5LongestGTime  Div5WheelsOff Div5TailNum  Unnamed: 109  
215759              NaN            NaN         NaN           NaN  
325019              NaN            NaN         NaN           NaN  
176064              NaN            NaN         NaN           NaN  
264848              NaN            NaN         NaN           NaN  
361698              NaN            NaN         NaN           NaN  

[5 rows x 110 columns]

In [158]:
df[df.columns[df.count() < 1000]].head()

DivReachedDest  DivActualElapsedTime  DivArrDelay  DivDistance  \
0             NaN                   NaN          NaN          NaN   
1             NaN                   NaN          NaN          NaN   
2             NaN                   NaN          NaN          NaN   
3             NaN                   NaN          NaN          NaN   
4             NaN                   NaN          NaN          NaN   

   Div1WheelsOff Div1TailNum Div2Airport  Div2AirportID  Div2AirportSeqID  \
0            NaN         NaN         NaN            NaN               NaN   
1            NaN         NaN         NaN            NaN               NaN   
2            NaN         NaN         NaN            NaN               NaN   
3            NaN         NaN         NaN            NaN               NaN   
4            NaN         NaN         NaN            NaN               NaN   

   Div2WheelsOn      ...       Div4TailNum  Div5Airport  Div5AirportID  \
0           NaN      ...               NaN          NaN            NaN   
1           NaN      ...               NaN          NaN            NaN   
2           NaN      ...               NaN          NaN            NaN   
3           NaN      ...               NaN          NaN            NaN   
4           NaN      ...               NaN          NaN            NaN   

  Div5AirportSeqID Div5WheelsOn  Div5TotalGTime  Div5LongestGTime  \
0              NaN          NaN             NaN               NaN   
1              NaN          NaN             NaN               NaN   
2              NaN          NaN             NaN               NaN   
3              NaN          NaN             NaN               NaN   
4              NaN          NaN             NaN               NaN   

   Div5WheelsOff  Div5TailNum  Unnamed: 109  
0            NaN          NaN           NaN  
1            NaN          NaN           NaN  
2            NaN          NaN           NaN  
3            NaN          NaN           NaN  
4            NaN          NaN           NaN  

[5 rows x 39 columns]

In [124]:
df.columns[df.count()<1000]

Index([u'DivReachedDest', u'DivActualElapsedTime', u'DivArrDelay',
       u'DivDistance', u'Div1WheelsOff', u'Div1TailNum', u'Div2Airport',
       u'Div2AirportID', u'Div2AirportSeqID', u'Div2WheelsOn',
       u'Div2TotalGTime', u'Div2LongestGTime', u'Div2WheelsOff',
       u'Div2TailNum', u'Div3Airport', u'Div3AirportID', u'Div3AirportSeqID',
       u'Div3WheelsOn', u'Div3TotalGTime', u'Div3LongestGTime',
       u'Div3WheelsOff', u'Div3TailNum', u'Div4Airport', u'Div4AirportID',
       u'Div4AirportSeqID', u'Div4WheelsOn', u'Div4TotalGTime',
       u'Div4LongestGTime', u'Div4WheelsOff', u'Div4TailNum', u'Div5Airport',
       u'Div5AirportID', u'Div5AirportSeqID', u'Div5WheelsOn',
       u'Div5TotalGTime', u'Div5LongestGTime', u'Div5WheelsOff',
       u'Div5TailNum', u'Unnamed: 109'],
      dtype='object')

In [159]:
df.reindex(columns=df.columns[df.count()<1000]).head()

DivReachedDest  DivActualElapsedTime  DivArrDelay  DivDistance  \
0             NaN                   NaN          NaN          NaN   
1             NaN                   NaN          NaN          NaN   
2             NaN                   NaN          NaN          NaN   
3             NaN                   NaN          NaN          NaN   
4             NaN                   NaN          NaN          NaN   

   Div1WheelsOff Div1TailNum Div2Airport  Div2AirportID  Div2AirportSeqID  \
0            NaN         NaN         NaN            NaN               NaN   
1            NaN         NaN         NaN            NaN               NaN   
2            NaN         NaN         NaN            NaN               NaN   
3            NaN         NaN         NaN            NaN               NaN   
4            NaN         NaN         NaN            NaN               NaN   

   Div2WheelsOn      ...       Div4TailNum  Div5Airport  Div5AirportID  \
0           NaN      ...               NaN          NaN            NaN   
1           NaN      ...               NaN          NaN            NaN   
2           NaN      ...               NaN          NaN            NaN   
3           NaN      ...               NaN          NaN            NaN   
4           NaN      ...               NaN          NaN            NaN   

  Div5AirportSeqID Div5WheelsOn  Div5TotalGTime  Div5LongestGTime  \
0              NaN          NaN             NaN               NaN   
1              NaN          NaN             NaN               NaN   
2              NaN          NaN             NaN               NaN   
3              NaN          NaN             NaN               NaN   
4              NaN          NaN             NaN               NaN   

   Div5WheelsOff  Div5TailNum  Unnamed: 109  
0            NaN          NaN           NaN  
1            NaN          NaN           NaN  
2            NaN          NaN           NaN  
3            NaN          NaN           NaN  
4            NaN          NaN           NaN  

[5 rows x 39 columns]

In [155]:
df.columns

Index([u'Year', u'Quarter', u'Month', u'DayofMonth', u'DayOfWeek',
       u'FlightDate', u'UniqueCarrier', u'AirlineID', u'Carrier', u'TailNum', 
       ...
       u'Div4TailNum', u'Div5Airport', u'Div5AirportID', u'Div5AirportSeqID',
       u'Div5WheelsOn', u'Div5TotalGTime', u'Div5LongestGTime',
       u'Div5WheelsOff', u'Div5TailNum', u'Unnamed: 109'],
      dtype='object', length=110)

In [160]:
df[df.columns[df.count() < 1000].values].head()

DivReachedDest  DivActualElapsedTime  DivArrDelay  DivDistance  \
0             NaN                   NaN          NaN          NaN   
1             NaN                   NaN          NaN          NaN   
2             NaN                   NaN          NaN          NaN   
3             NaN                   NaN          NaN          NaN   
4             NaN                   NaN          NaN          NaN   

   Div1WheelsOff Div1TailNum Div2Airport  Div2AirportID  Div2AirportSeqID  \
0            NaN         NaN         NaN            NaN               NaN   
1            NaN         NaN         NaN            NaN               NaN   
2            NaN         NaN         NaN            NaN               NaN   
3            NaN         NaN         NaN            NaN               NaN   
4            NaN         NaN         NaN            NaN               NaN   

   Div2WheelsOn      ...       Div4TailNum  Div5Airport  Div5AirportID  \
0           NaN      ...               NaN          NaN            NaN   
1           NaN      ...               NaN          NaN            NaN   
2           NaN      ...               NaN          NaN            NaN   
3           NaN      ...               NaN          NaN            NaN   
4           NaN      ...               NaN          NaN            NaN   

  Div5AirportSeqID Div5WheelsOn  Div5TotalGTime  Div5LongestGTime  \
0              NaN          NaN             NaN               NaN   
1              NaN          NaN             NaN               NaN   
2              NaN          NaN             NaN               NaN   
3              NaN          NaN             NaN               NaN   
4              NaN          NaN             NaN               NaN   

   Div5WheelsOff  Div5TailNum  Unnamed: 109  
0            NaN          NaN           NaN  
1            NaN          NaN           NaN  
2            NaN          NaN           NaN  
3            NaN          NaN           NaN  
4            NaN          NaN           NaN  

[5 rows x 39 columns]

In [166]:
df[df.columns[df.columns.str.contains('Origin')]]

OriginAirportID  OriginAirportSeqID  OriginCityMarketID Origin  \
0                 12478             1247802               31703    JFK   
1                 12478             1247802               31703    JFK   
2                 12478             1247802               31703    JFK   
3                 12478             1247802               31703    JFK   
4                 12478             1247802               31703    JFK   
5                 12478             1247802               31703    JFK   
6                 12478             1247802               31703    JFK   
7                 12478             1247802               31703    JFK   
8                 12478             1247802               31703    JFK   
9                 12478             1247802               31703    JFK   
10                12478             1247802               31703    JFK   
11                12478             1247802               31703    JFK   
12                12478             1247802               31703    JFK   
13                12478             1247802               31703    JFK   
14                12478             1247802               31703    JFK   
15                12478             1247802               31703    JFK   
16                12478             1247802               31703    JFK   
17                12478             1247802               31703    JFK   
18                12478             1247802               31703    JFK   
19                12478             1247802               31703    JFK   
20                12478             1247802               31703    JFK   
21                12478             1247802               31703    JFK   
22                12478             1247802               31703    JFK   
23                12478             1247802               31703    JFK   
24                12478             1247802               31703    JFK   
25                12478             1247802               31703    JFK   
26                12478             1247802               31703    JFK   
27                12478             1247802               31703    JFK   
28                12478             1247802               31703    JFK   
29                12478             1247802               31703    JFK   
...                 ...                 ...                 ...    ...   
469938            13796             1379603               32457    OAK   
469939            13796             1379603               32457    OAK   
469940            13796             1379603               32457    OAK   
469941            13796             1379603               32457    OAK   
469942            13796             1379603               32457    OAK   
469943            13796             1379603               32457    OAK   
469944            13796             1379603               32457    OAK   
469945            13796             1379603               32457    OAK   
469946            13796             1379603               32457    OAK   
469947            13796             1379603               32457    OAK   
469948            13796             1379603               32457    OAK   
469949            13796             1379603               32457    OAK   
469950            13796             1379603               32457    OAK   
469951            13796             1379603               32457    OAK   
469952            13796             1379603               32457    OAK   
469953            13796             1379603               32457    OAK   
469954            13796             1379603               32457    OAK   
469955            13796             1379603               32457    OAK   
469956            13796             1379603               32457    OAK   
469957            13796             1379603               32457    OAK   
469958            13796             1379603               32457    OAK   
469959            13796             1379603               32457    OAK   
469960      

In [167]:
cols_to_keep = pd.Index(['Origin','OriginCityName','OriginStateName'])

In [168]:
cols_to_drop = df.columns.difference(cols_to_keep)

In [169]:
cols_to_drop

Index([u'ActualElapsedTime', u'AirTime', u'AirlineID', u'ArrDel15',
       u'ArrDelay', u'ArrDelayMinutes', u'ArrTime', u'ArrTimeBlk',
       u'ArrivalDelayGroups', u'CRSArrTime', 
       ...
       u'TailNum', u'TaxiIn', u'TaxiOut', u'TotalAddGTime', u'UniqueCarrier',
       u'Unnamed: 109', u'WeatherDelay', u'WheelsOff', u'WheelsOn', u'Year'],
      dtype='object', length=107)

In [172]:
df[cols_to_keep]

Origin OriginCityName OriginStateName
0         JFK   New York, NY        New York
1         JFK   New York, NY        New York
2         JFK   New York, NY        New York
3         JFK   New York, NY        New York
4         JFK   New York, NY        New York
5         JFK   New York, NY        New York
6         JFK   New York, NY        New York
7         JFK   New York, NY        New York
8         JFK   New York, NY        New York
9         JFK   New York, NY        New York
10        JFK   New York, NY        New York
11        JFK   New York, NY        New York
12        JFK   New York, NY        New York
13        JFK   New York, NY        New York
14        JFK   New York, NY        New York
15        JFK   New York, NY        New York
16        JFK   New York, NY        New York
17        JFK   New York, NY        New York
18        JFK   New York, NY        New York
19        JFK   New York, NY        New York
20        JFK   New York, NY        New York
21        JFK   New York, NY        New York
22        JFK   New York, NY        New York
23        JFK   New York, NY        New York
24        JFK   New York, NY        New York
25        JFK   New York, NY        New York
26        JFK   New York, NY        New York
27        JFK   New York, NY        New York
28        JFK   New York, NY        New York
29        JFK   New York, NY        New York
...       ...            ...             ...
469938    OAK    Oakland, CA      California
469939    OAK    Oakland, CA      California
469940    OAK    Oakland, CA      California
469941    OAK    Oakland, CA      California
469942    OAK    Oakland, CA      California
469943    OAK    Oakland, CA      California
469944    OAK    Oakland, CA      California
469945    OAK    Oakland, CA      California
469946    OAK    Oakland, CA      California
469947    OAK    Oakland, CA      California
469948    OAK    Oakland, CA      California
469949    OAK    Oakland, CA      California
469950    OAK    Oakland, CA      California
469951    OAK    Oakland, CA      California
469952    OAK    Oakland, CA      California
469953    OAK    Oakland, CA      California
469954    OAK    Oakland, CA      California
469955    OAK    Oakland, CA      California
469956    OAK    Oakland, CA      California
469957    OAK    Oakland, CA      California
469958    OAK    Oakland, CA      California
469959    OAK    Oakland, CA      California
469960    OAK    Oakland, CA      California
469961    OAK    Oakland, CA      California
469962    OAK    Oakland, CA      California
469963    OAK    Oakland, CA      California
469964    OAK    Oakland, CA      California
469965    OAK    Oakland, CA      California
469966    OAK    Oakland, CA      California
469967    IAH    Houston, TX           Texas

[469968 rows x 3 columns]

In [177]:
df.columns[df.columns.str.contains('Origin')].difference(cols_to_keep)

Index([u'OriginAirportID', u'OriginAirportSeqID', u'OriginCityMarketID',
       u'OriginState', u'OriginStateFips', u'OriginWac'],
      dtype='object')

In [179]:
cols_to_drop=df.columns[df.columns.str.contains('Origin')].difference(cols_to_keep)

In [180]:
df.drop(cols_to_drop,axis=1)

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
0       2015        1      1           1          4  2015-01-01            AA   
1       2015        1      1           2          5  2015-01-02            AA   
2       2015        1      1           3          6  2015-01-03            AA   
3       2015        1      1           4          7  2015-01-04            AA   
4       2015        1      1           5          1  2015-01-05            AA   
5       2015        1      1           6          2  2015-01-06            AA   
6       2015        1      1           7          3  2015-01-07            AA   
7       2015        1      1           8          4  2015-01-08            AA   
8       2015        1      1           9          5  2015-01-09            AA   
9       2015        1      1          10          6  2015-01-10            AA   
10      2015        1      1          11          7  2015-01-11            AA   
11      2015        1      1          12          1  2015-01-12            AA   
12      2015        1      1          13          2  2015-01-13            AA   
13      2015        1      1          14          3  2015-01-14            AA   
14      2015        1      1          15          4  2015-01-15            AA   
15      2015        1      1          16          5  2015-01-16            AA   
16      2015        1      1          17          6  2015-01-17            AA   
17      2015        1      1          18          7  2015-01-18            AA   
18      2015        1      1          19          1  2015-01-19            AA   
19      2015        1      1          20          2  2015-01-20            AA   
20      2015        1      1          21          3  2015-01-21            AA   
21      2015        1      1          22          4  2015-01-22            AA   
22      2015        1      1          23          5  2015-01-23            AA   
23      2015        1      1          24          6  2015-01-24            AA   
24      2015        1      1          25          7  2015-01-25            AA   
25      2015        1      1          26          1  2015-01-26            AA   
26      2015        1      1          27          2  2015-01-27            AA   
27      2015        1      1          28          3  2015-01-28            AA   
28      2015        1      1          29          4  2015-01-29            AA   
29      2015        1      1          30          5  2015-01-30            AA   
...      ...      ...    ...         ...        ...         ...           ...   
469938  2015        1      1           3          6  2015-01-03            NK   
469939  2015        1      1           4          7  2015-01-04            NK   
469940  2015        1      1           5          1  2015-01-05            NK   
469941  2015        1      1           6          2  2015-01-06            NK   
469942  2015        1      1           7          3  2015-01-07            NK   
469943  2015        1      1           8          4  2015-01-08            NK   
469944  2015        1      1           9          5  2015-01-09            NK   
469945  2015        1      1          10          6  2015-01-10            NK   
469946  2015        1      1          11          7  2015-01-11            NK   
469947  2015        1      1          12          1  2015-01-12            NK   
469948  2015        1      1          13          2  2015-01-13            NK   
469949  2015        1      1          14          3  2015-01-14            NK   
469950  2015        1      1          15          4  2015-01-15            NK   
469951  2015        1      1          16          5  2015-01-16            NK   
469952  2015        1      1          17          6  2015-01-17            NK   
469953  2015        1      1          18          7  2015-01-18            NK   
469954  2015        1      1          19          1  2015-01-19            NK   
469955  2015        1      1          2

In [181]:
df.sample(5)

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
99515   2015        1      1          13          2  2015-01-13            DL   
234248  2015        1      1          31          6  2015-01-31            WN   
42961   2015        1      1           3          6  2015-01-03            AS   
256316  2015        1      1          16          5  2015-01-16            OO   
432213  2015        1      1          21          3  2015-01-21            F9   

        AirlineID Carrier TailNum      ...       Div4TailNum  Div5Airport  \
99515       19790      DL  N960DL      ...               NaN          NaN   
234248      19393      WN  N643SW      ...               NaN          NaN   
42961       19930      AS  N607AS      ...               NaN          NaN   
256316      20304      OO  N227AG      ...               NaN          NaN   
432213      20436      F9  N206FR      ...               NaN          NaN   

        Div5AirportID  Div5AirportSeqID Div5WheelsOn Div5TotalGTime  \
99515             NaN               NaN          NaN            NaN   
234248            NaN               NaN          NaN            NaN   
42961             NaN               NaN          NaN            NaN   
256316            NaN               NaN          NaN            NaN   
432213            NaN               NaN          NaN            NaN   

       Div5LongestGTime  Div5WheelsOff Div5TailNum  Unnamed: 109  
99515               NaN            NaN         NaN           NaN  
234248              NaN            NaN         NaN           NaN  
42961               NaN            NaN         NaN           NaN  
256316              NaN            NaN         NaN           NaN  
432213              NaN            NaN         NaN           NaN  

[5 rows x 110 columns]

In [188]:
df['DepHour']=df['DepTime'].fillna(0).apply(lambda row : int(row/100))

In [189]:
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
0       2015        1      1           1          4  2015-01-01            AA   
1       2015        1      1           2          5  2015-01-02            AA   
2       2015        1      1           3          6  2015-01-03            AA   
3       2015        1      1           4          7  2015-01-04            AA   
4       2015        1      1           5          1  2015-01-05            AA   
5       2015        1      1           6          2  2015-01-06            AA   
6       2015        1      1           7          3  2015-01-07            AA   
7       2015        1      1           8          4  2015-01-08            AA   
8       2015        1      1           9          5  2015-01-09            AA   
9       2015        1      1          10          6  2015-01-10            AA   
10      2015        1      1          11          7  2015-01-11            AA   
11      2015        1      1          12          1  2015-01-12            AA   
12      2015        1      1          13          2  2015-01-13            AA   
13      2015        1      1          14          3  2015-01-14            AA   
14      2015        1      1          15          4  2015-01-15            AA   
15      2015        1      1          16          5  2015-01-16            AA   
16      2015        1      1          17          6  2015-01-17            AA   
17      2015        1      1          18          7  2015-01-18            AA   
18      2015        1      1          19          1  2015-01-19            AA   
19      2015        1      1          20          2  2015-01-20            AA   
20      2015        1      1          21          3  2015-01-21            AA   
21      2015        1      1          22          4  2015-01-22            AA   
22      2015        1      1          23          5  2015-01-23            AA   
23      2015        1      1          24          6  2015-01-24            AA   
24      2015        1      1          25          7  2015-01-25            AA   
25      2015        1      1          26          1  2015-01-26            AA   
26      2015        1      1          27          2  2015-01-27            AA   
27      2015        1      1          28          3  2015-01-28            AA   
28      2015        1      1          29          4  2015-01-29            AA   
29      2015        1      1          30          5  2015-01-30            AA   
...      ...      ...    ...         ...        ...         ...           ...   
469938  2015        1      1           3          6  2015-01-03            NK   
469939  2015        1      1           4          7  2015-01-04            NK   
469940  2015        1      1           5          1  2015-01-05            NK   
469941  2015        1      1           6          2  2015-01-06            NK   
469942  2015        1      1           7          3  2015-01-07            NK   
469943  2015        1      1           8          4  2015-01-08            NK   
469944  2015        1      1           9          5  2015-01-09            NK   
469945  2015        1      1          10          6  2015-01-10            NK   
469946  2015        1      1          11          7  2015-01-11            NK   
469947  2015        1      1          12          1  2015-01-12            NK   
469948  2015        1      1          13          2  2015-01-13            NK   
469949  2015        1      1          14          3  2015-01-14            NK   
469950  2015        1      1          15          4  2015-01-15            NK   
469951  2015        1      1          16          5  2015-01-16            NK   
469952  2015        1      1          17          6  2015-01-17            NK   
469953  2015        1      1          18          7  2015-01-18            NK   
469954  2015        1      1          19          1  2015-01-19            NK   
469955  2015        1      1          2