In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
x = Series(np.arange(10)*1000)

In [4]:
x.values

array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])

In [5]:
x.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [6]:
x[1]

1000

In [7]:
x > 5000

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool

In [8]:
x[x > 5000]

6    6000
7    7000
8    8000
9    9000
dtype: int64

In [9]:
5000 in x

False

In [10]:
8 in x

True

In [11]:
y = Series(np.arange(10)*1000, index=np.arange(2,12))

In [12]:
x+y

0       NaN
1       NaN
2      2000
3      4000
4      6000
5      8000
6     10000
7     12000
8     14000
9     16000
10      NaN
11      NaN
dtype: float64

In [13]:
x[5]=5
x

0       0
1    1000
2    2000
3    3000
4    4000
5       5
6    6000
7    7000
8    8000
9    9000
dtype: int64

In [16]:
(x+y)[(x+y).notnull()]

2     2000
3     4000
4     6000
5     3005
6    10000
7    12000
8    14000
9    16000
dtype: float64

In [176]:
x

0       0
1    1000
2    2000
3    3000
4    4000
5       5
6    6000
7    7000
8    8000
9    9000
dtype: int64

In [177]:
x.index = range(10,20)
x

10       0
11    1000
12    2000
13    3000
14    4000
15       5
16    6000
17    7000
18    8000
19    9000
dtype: int64

In [178]:
x

10       0
11    1000
12    2000
13    3000
14    4000
15       5
16    6000
17    7000
18    8000
19    9000
dtype: int64

In [179]:
x = DataFrame(np.arange(15).reshape(5,3))
x

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [180]:
x.index = range(1,6)
x.columns=['c1','c2','c3']
x

c1  c2  c3
1   0   1   2
2   3   4   5
3   6   7   8
4   9  10  11
5  12  13  14

In [38]:
x = DataFrame(np.ones(100).reshape(10,10), index=range(1,11), columns=range(1,11))
for i in range(1,11):
    x.ix[i] = x.ix[i]*i
for i in range(1,11):
    x[i] = x[i]*i
x

1   2   3   4   5   6   7   8   9    10
1    1   2   3   4   5   6   7   8   9   10
2    2   4   6   8  10  12  14  16  18   20
3    3   6   9  12  15  18  21  24  27   30
4    4   8  12  16  20  24  28  32  36   40
5    5  10  15  20  25  30  35  40  45   50
6    6  12  18  24  30  36  42  48  54   60
7    7  14  21  28  35  42  49  56  63   70
8    8  16  24  32  40  48  56  64  72   80
9    9  18  27  36  45  54  63  72  81   90
10  10  20  30  40  50  60  70  80  90  100

In [39]:
x[2] = np.nan
x[3] = range(10)
x.ix[4] = np.random.randn(10)
np.floor(x) 

1   2   3   4   5   6   7   8   9    10
1    1 NaN   0   4   5   6   7   8   9   10
2    2 NaN   1   8  10  12  14  16  18   20
3    3 NaN   2  12  15  18  21  24  27   30
4   -1  -1  -1  -1  -1  -1  -1   1   0    1
5    5 NaN   4  20  25  30  35  40  45   50
6    6 NaN   5  24  30  36  42  48  54   60
7    7 NaN   6  28  35  42  49  56  63   70
8    8 NaN   7  32  40  48  56  64  72   80
9    9 NaN   8  36  45  54  63  72  81   90
10  10 NaN   9  40  50  60  70  80  90  100

In [40]:
x.ix[3].index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [41]:
x[3] > 5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
Name: 3, dtype: bool

In [44]:
x['New'] = x[3] > 5
x['new2'] = x[3]+x[6]
x

1         2         3         4          5          6          7  \
1    1.000000       NaN  0.000000   4.00000   5.000000   6.000000   7.000000   
2    2.000000       NaN  1.000000   8.00000  10.000000  12.000000  14.000000   
3    3.000000       NaN  2.000000  12.00000  15.000000  18.000000  21.000000   
4   -0.430508 -0.261869 -0.409149  -0.67084  -0.865099  -0.222677  -0.016486   
5    5.000000       NaN  4.000000  20.00000  25.000000  30.000000  35.000000   
6    6.000000       NaN  5.000000  24.00000  30.000000  36.000000  42.000000   
7    7.000000       NaN  6.000000  28.00000  35.000000  42.000000  49.000000   
8    8.000000       NaN  7.000000  32.00000  40.000000  48.000000  56.000000   
9    9.000000       NaN  8.000000  36.00000  45.000000  54.000000  63.000000   
10  10.000000       NaN  9.000000  40.00000  50.000000  60.000000  70.000000   

            8          9          10    New       new2  
1    8.000000   9.000000   10.000000  False   6.000000  
2   16.000000  18.000000   20.000000  False  13.000000  
3   24.000000  27.000000   30.000000  False  20.000000  
4    1.039498   0.961085    1.523655  False  -0.631826  
5   40.000000  45.000000   50.000000  False  34.000000  
6   48.000000  54.000000   60.000000  False  41.000000  
7   56.000000  63.000000   70.000000   True  48.000000  
8   64.000000  72.000000   80.000000   True  55.000000  
9   72.000000  81.000000   90.000000   True  62.000000  
10  80.000000  90.000000  100.000000   True  69.000000

In [43]:
x.values

array([[1.0, nan, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, False, 6.0],
       [2.0, nan, 1.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, False, 13.0],
       [3.0, nan, 2.0, 12.0, 15.0, 18.0, 21.0, 24.0, 27.0, 30.0, False,
        20.0],
       [-0.43050845437634916, -0.26186913493598807, -0.4091489050289288,
        -0.6708401312303509, -0.8650993696353096, -0.22267689806515653,
        -0.0164864975631145, 1.0394978807218844, 0.9610854911648657,
        1.523654655158375, False, -0.6318258030940853],
       [5.0, nan, 4.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0, 50.0, False,
        34.0],
       [6.0, nan, 5.0, 24.0, 30.0, 36.0, 42.0, 48.0, 54.0, 60.0, False,
        41.0],
       [7.0, nan, 6.0, 28.0, 35.0, 42.0, 49.0, 56.0, 63.0, 70.0, True, 48.0],
       [8.0, nan, 7.0, 32.0, 40.0, 48.0, 56.0, 64.0, 72.0, 80.0, True, 55.0],
       [9.0, nan, 8.0, 36.0, 45.0, 54.0, 63.0, 72.0, 81.0, 90.0, True, 62.0],
       [10.0, nan, 9.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0, True,
        69.0

In [27]:
x.columns

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, u'New', u'new2'], dtype='object')

In [28]:
x.index[2:4]

Int64Index([3, 4], dtype='int64')

In [29]:
x.index[3]='i3'

TypeError: Indexes does not support mutable operations

In [30]:
x = Series([2,3,4], index=[1,'l2','l3'])
x

1     2
l2    3
l3    4
dtype: int64

In [31]:
'l2' in x

True

In [32]:
'l2' in x.index

True

In [33]:
i1 = x.index
i1

Index([1, u'l2', u'l3'], dtype='object')

In [34]:
i2 = x.index
i2

Index([1, u'l2', u'l3'], dtype='object')

In [35]:
i1.append(i2)
i1

Index([1, u'l2', u'l3'], dtype='object')

In [36]:
i1.union(i2)

Index([1, u'l2', u'l3'], dtype='object')

In [45]:
x.columns.isin([3,'3','new2'])

array([False, False,  True, False, False, False, False, False, False,
       False, False,  True], dtype=bool)

In [46]:
i1.delete(5)

IndexError: index 5 is out of bounds for axis 0 with size 3

In [47]:
i1

Index([1, u'l2', u'l3'], dtype='object')

In [48]:
pd.unique(i1.union(i2))

array([1, 'l2', 'l3'], dtype=object)

In [49]:
x

1         2         3         4          5          6          7  \
1    1.000000       NaN  0.000000   4.00000   5.000000   6.000000   7.000000   
2    2.000000       NaN  1.000000   8.00000  10.000000  12.000000  14.000000   
3    3.000000       NaN  2.000000  12.00000  15.000000  18.000000  21.000000   
4   -0.430508 -0.261869 -0.409149  -0.67084  -0.865099  -0.222677  -0.016486   
5    5.000000       NaN  4.000000  20.00000  25.000000  30.000000  35.000000   
6    6.000000       NaN  5.000000  24.00000  30.000000  36.000000  42.000000   
7    7.000000       NaN  6.000000  28.00000  35.000000  42.000000  49.000000   
8    8.000000       NaN  7.000000  32.00000  40.000000  48.000000  56.000000   
9    9.000000       NaN  8.000000  36.00000  45.000000  54.000000  63.000000   
10  10.000000       NaN  9.000000  40.00000  50.000000  60.000000  70.000000   

            8          9          10    New       new2  
1    8.000000   9.000000   10.000000  False   6.000000  
2   16.000000  18.000000   20.000000  False  13.000000  
3   24.000000  27.000000   30.000000  False  20.000000  
4    1.039498   0.961085    1.523655  False  -0.631826  
5   40.000000  45.000000   50.000000  False  34.000000  
6   48.000000  54.000000   60.000000  False  41.000000  
7   56.000000  63.000000   70.000000   True  48.000000  
8   64.000000  72.000000   80.000000   True  55.000000  
9   72.000000  81.000000   90.000000   True  62.000000  
10  80.000000  90.000000  100.000000   True  69.000000

In [50]:
df = DataFrame(np.arange(9).reshape(3,3), index=['a','c','d'], columns =['c1','c3','c4'])
df

c1  c3  c4
a   0   1   2
c   3   4   5
d   6   7   8

In [51]:
df.reindex(['a','b','c','d'],method='bfill')

c1  c3  c4
a   0   1   2
b   3   4   5
c   3   4   5
d   6   7   8

In [52]:
df = df.reindex(index=['a','b','c','d'],method='bfill', columns=['c1','c2','c3','c4'])

In [53]:
df

c1  c2  c3  c4
a   0 NaN   1   2
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [54]:
df.drop(['b','d'])

c1  c2  c3  c4
a   0 NaN   1   2
c   3 NaN   4   5

In [55]:
df.drop(['c2'], axis=1)

c1  c3  c4
a   0   1   2
b   3   4   5
c   3   4   5
d   6   7   8

In [56]:
df

c1  c2  c3  c4
a   0 NaN   1   2
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [57]:
df[['c1','c3']]

c1  c3
a   0   1
b   3   4
c   3   4
d   6   7

In [58]:
df.ix['b':'d']

c1  c2  c3  c4
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [59]:
df

c1  c2  c3  c4
a   0 NaN   1   2
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [60]:
df[:2]

c1  c2  c3  c4
a   0 NaN   1   2
b   3 NaN   4   5

In [61]:
df[df['c3'] > 3]

c1  c2  c3  c4
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [62]:
print(df >3)
df[df > 3]

      c1     c2     c3     c4
a  False  False  False  False
b  False  False   True   True
c  False  False   True   True
d   True  False   True   True


c1  c2  c3  c4
a NaN NaN NaN NaN
b NaN NaN   4   5
c NaN NaN   4   5
d   6 NaN   7   8

In [63]:
df[df > 3]

c1  c2  c3  c4
a NaN NaN NaN NaN
b NaN NaN   4   5
c NaN NaN   4   5
d   6 NaN   7   8

In [64]:
df

c1  c2  c3  c4
a   0 NaN   1   2
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [65]:
df.ix[['b','c']][['c3','c1']]

c3  c1
b   4   3
c   4   3

In [66]:
df

c1  c2  c3  c4
a   0 NaN   1   2
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [67]:
df.ix[['b','a']]

c1  c2  c3  c4
b   3 NaN   4   5
a   0 NaN   1   2

In [68]:
df[df['c3'] > 3]

c1  c2  c3  c4
b   3 NaN   4   5
c   3 NaN   4   5
d   6 NaN   7   8

In [69]:
df[['c3':'c4']]

SyntaxError: invalid syntax (<ipython-input-69-5539f1a8aef0>, line 1)

In [72]:
list('abcd')

['a', 'b', 'c', 'd']

In [80]:
x1 = DataFrame(np.arange(9).reshape(3,3), columns=list('abc'), index=list('wxy'))
x1

a  b  c
w  0  1  2
x  3  4  5
y  6  7  8

In [81]:
x2 = DataFrame(np.arange(9).reshape(3,3), columns=list('abd'), index=list('wxz'))
x2

a  b  d
w  0  1  2
x  3  4  5
z  6  7  8

In [82]:
x1+x2

a   b   c   d
w   0   2 NaN NaN
x   6   8 NaN NaN
y NaN NaN NaN NaN
z NaN NaN NaN NaN

In [83]:
x1.add(x2, fill_value=10)

a   b   c   d
w   0   2  12  12
x   6   8  15  15
y  16  17  18 NaN
z  16  17 NaN  18

In [84]:
x1 = DataFrame(np.arange(9).reshape(3,3), columns=list('abc'), index=list('xyz'))
x1

a  b  c
x  0  1  2
y  3  4  5
z  6  7  8

In [98]:
s1 = x1.ix['x']
s1

a    0
b    1
c    2
Name: x, dtype: int64

In [100]:
x1 + s1

a  b   c
x  0  2   4
y  3  5   7
z  6  8  10

In [101]:
s1 = x1['a']
s1

x    0
y    3
z    6
Name: a, dtype: int64

In [102]:
x1.add(s1,axis=0)

a   b   c
x   0   1   2
y   6   7   8
z  12  13  14

In [104]:
x1 = np.abs(DataFrame(np.random.randn(9).reshape(3,3), columns=list('abc'), index=list('xyz')))
x1

a         b         c
x  1.262862  0.662208  0.011153
y  0.257851  0.767629  0.112525
z  0.827792  1.686294  0.665811

In [108]:
x1['a'].max()-x1['a'].min()

1.0050113458795078

In [109]:
f = lambda x: x.max() - x.min()
x1.apply(f)

a    1.005011
b    1.024086
c    0.654657
dtype: float64

In [110]:
x1.ix['x'].max()-x1.ix['x'].min()

1.2517085681914213

In [114]:
x1.apply(f, axis=1)

x    1.251709
y    0.655105
z    1.020483
dtype: float64

In [117]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [118]:
x1.apply(f)

a         b         c
min  0.257851  0.662208  0.011153
max  1.262862  1.686294  0.665811

In [137]:
format = lambda x: '%.2f' % x
x1

a         b         c
x  1.262862  0.662208  0.011153
y  0.257851  0.767629  0.112525
z  0.827792  1.686294  0.665811

In [138]:
x1.applymap(format)

a     b     c
x  1.26  0.66  0.01
y  0.26  0.77  0.11
z  0.83  1.69  0.67

In [142]:
x1['c'].map(format)

x    0.01
y    0.11
z    0.67
Name: c, dtype: object

In [158]:
s1 = Series([0,2,1,3], index=list('dabc'))
s1

d    0
a    2
b    1
c    3
dtype: int64

In [159]:
s1.sort_index()

a    2
b    1
c    3
d    0
dtype: int64

In [175]:
d1 = np.abs(DataFrame(np.random.randn(9).reshape(3,3), columns=list('cab'), index=list('zxy')))
d1

c         a         b
z  0.850955  0.348508  1.022901
x  0.385062  0.053591  0.070473
y  0.009457  0.634771  1.172598

In [176]:
d1.sort_index()

c         a         b
x  0.385062  0.053591  0.070473
y  0.009457  0.634771  1.172598
z  0.850955  0.348508  1.022901

In [178]:
d1.sort_index(axis=1,ascending=False)

c         b         a
z  0.850955  1.022901  0.348508
x  0.385062  0.070473  0.053591
y  0.009457  1.172598  0.634771

In [179]:
# sort by values instead indexes
s1.order(ascending=False)

c    3
a    2
b    1
d    0
dtype: int64

In [180]:
d1.sort_index(by='a')

c         a         b
x  0.385062  0.053591  0.070473
z  0.850955  0.348508  1.022901
y  0.009457  0.634771  1.172598