In [310]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series,DataFrame

## Get your data into a DataFrame

In [3]:
!ls -l

total 207268
-rw-rw-r--. 1 dsc vboxsf    311761 Dec 18 21:52 grouping.ipynb
-rw-rw-r--. 1 dsc dsc       242020 Dec 19 13:21 load_and_examples.ipynb
-rw-r--r--. 1 dsc vboxsf 211633432 Apr 16  2015 On_Time_On_Time_Performance_2015_1.csv
-rw-r--r--. 1 dsc vboxsf     12054 Apr 16  2015 readme.html
-rw-rw-r--. 1 dsc vboxsf     27904 Dec 18 21:52 reviewing_pandas.ipynb
-rw-r--r--. 1 dsc vboxsf       864 Dec 30 10:45 studying_cheat_sheet_pandas_dataframe.ipynb


In [162]:
# From csv file
df1 = pd.read_csv("On_Time_On_Time_Performance_2015_1.csv", low_memory=False)

In [3]:
# From array
df0 = DataFrame(np.array([range(6),range(6,12),range(12,18)]))
df0

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17

In [147]:
df0.index=[1000,2000,3000]
df0.columns=['c1','c2','c3','c4','c5','c6']
df0

c1  c2  c3  c4  c5  c6
1000   0   1   2   3   4   5
2000   6   7   8   9  10  11
3000  12  13  14  15  16  17

In [63]:
# From series
serie1 = Series(range(6))
serie2 = serie1 * serie1
serie2.index = serie2.index+2
df1 = pd.concat([serie1,serie2], axis=1)
df1

0   1
0   0 NaN
1   1 NaN
2   2   0
3   3   1
4   4   4
5   5   9
6 NaN  16
7 NaN  25

In [66]:
# From dictionaries by columns
df1 = DataFrame.from_dict({'c1':serie1,'c2':serie2})
df1

c1  c2
0   0 NaN
1   1 NaN
2   2   0
3   3   1
4   4   4
5   5   9
6 NaN  16
7 NaN  25

In [67]:
# From dictionaries by rows
df2 = DataFrame.from_dict({'r1':serie1,'r2':serie2}, orient='index')
df2

0   1  2  3  4  5   6   7
r1   0   1  2  3  4  5 NaN NaN
r2 NaN NaN  0  1  4  9  16  25

In [114]:
# fake dataframes (useful for testing)
df3 = DataFrame(np.random.randn(50,5))
df3.index = pd.date_range('1/1/2006', periods=len(df3), freq='M')
df3.columns = ['C'+str(i) for i in range(5)]
df3.tail()

c0        c1        c2        c3        c4
2009-10-31  0.257276 -1.957165 -0.344836 -1.367572  0.214371
2009-11-30  0.957304  1.844745 -0.090272  0.398684 -0.087502
2009-12-31 -0.367741 -0.846471 -1.415575  2.131814 -0.362652
2010-01-31 -0.376740  0.577174  0.266043 -1.108525 -0.319921
2010-02-28  0.471784 -1.436758  1.075515 -0.240659  0.185853

In [126]:
np.random.rand(5)

array([ 0.7586669 ,  0.59008266,  0.54834192,  0.65912398,  0.07494704])

In [127]:
np.random.randn(5)

array([-0.27712135,  0.69560897,  0.32491045,  0.77349243, -1.85451276])

In [136]:
np.random.choice(['a','b','c'])

'c'

## Saving a Dataframe

In [173]:
# To csv
df3.to_csv("/tmp/df3.csv", sep=";", encoding='utf-8')

In [174]:
# To excel
df3.to_excel("/tmp/df3.xls",'sheet1')

In [175]:
# To dictionary
df0.to_dict()

{'c1': {1000: 0, 2000: 6, 3000: 12},
 'c2': {1000: 1, 2000: 7, 3000: 13},
 'c3': {1000: 2, 2000: 8, 3000: 14},
 'c4': {1000: 3, 2000: 9, 3000: 15},
 'c5': {1000: 4, 2000: 10, 3000: 16},
 'c6': {1000: 5, 2000: 11, 3000: 17}}

In [176]:
df0.to_string()

u'      c1  c2  c3  c4  c5  c6\n1000   0   1   2   3   4   5\n2000   6   7   8   9  10  11\n3000  12  13  14  15  16  17'

## Working with the whole DataFrame

In [295]:
# Info about Dataframes
df0['c4'] = [20,25,15]
df0['c7']='jalmen'
df0

c1  c2  c3  c4  c5  c6      c7
1000   0   1   2  20   4   5  jalmen
2000   6   7   8  25  10  11  jalmen
3000  12  13  14  15  16  17  jalmen

In [296]:
df0.T

1000    2000    3000
c1       0       6      12
c2       1       7      13
c3       2       8      14
c4      20      25      15
c5       4      10      16
c6       5      11      17
c7  jalmen  jalmen  jalmen

In [297]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 1000 to 3000
Data columns (total 7 columns):
c1    3 non-null int64
c2    3 non-null int64
c3    3 non-null int64
c4    3 non-null int64
c5    3 non-null int64
c6    3 non-null int64
c7    3 non-null object
dtypes: int64(6), object(1)
memory usage: 192.0+ bytes


In [298]:
df0.describe()

c1  c2  c3    c4  c5  c6
count   3   3   3   3.0   3   3
mean    6   7   8  20.0  10  11
std     6   6   6   5.0   6   6
min     0   1   2  15.0   4   5
25%     3   4   5  17.5   7   8
50%     6   7   8  20.0  10  11
75%     9  10  11  22.5  13  14
max    12  13  14  25.0  16  17

In [299]:
df0.head(1)

c1  c2  c3  c4  c5  c6      c7
1000   0   1   2  20   4   5  jalmen

In [300]:
df0.tail(1)

c1  c2  c3  c4  c5  c6      c7
3000  12  13  14  15  16  17  jalmen

In [301]:
df0.sample(1)

c1  c2  c3  c4  c5  c6      c7
3000  12  13  14  15  16  17  jalmen

In [302]:
# Dataframe attributes
df0.axes

[Int64Index([1000, 2000, 3000], dtype='int64'),
 Index([u'c1', u'c2', u'c3', u'c4', u'c5', u'c6', u'c7'], dtype='object')]

In [303]:
df0.dtypes

c1     int64
c2     int64
c3     int64
c4     int64
c5     int64
c6     int64
c7    object
dtype: object

In [304]:
print len(df0)
print df0.ndim
print df0.shape
print df0.size

3
2
(3, 7)
21


In [305]:
df0.index

Int64Index([1000, 2000, 3000], dtype='int64')

In [306]:
df0.columns

Index([u'c1', u'c2', u'c3', u'c4', u'c5', u'c6', u'c7'], dtype='object')

In [307]:
df0.values

array([[0, 1, 2, 20, 4, 5, 'jalmen'],
       [6, 7, 8, 25, 10, 11, 'jalmen'],
       [12, 13, 14, 15, 16, 17, 'jalmen']], dtype=object)

In [308]:
# Dataframe methods
df0.rank()

c1  c2  c3  c4  c5  c6  c7
1000   1   1   1   2   1   1   2
2000   2   2   2   3   2   2   2
3000   3   3   3   1   3   3   2

In [309]:
# It does not change DataFrame
df0.sort('c4', ascending=False)

c1  c2  c3  c4  c5  c6      c7
2000   6   7   8  25  10  11  jalmen
1000   0   1   2  20   4   5  jalmen
3000  12  13  14  15  16  17  jalmen

In [310]:
df0

c1  c2  c3  c4  c5  c6      c7
1000   0   1   2  20   4   5  jalmen
2000   6   7   8  25  10  11  jalmen
3000  12  13  14  15  16  17  jalmen

In [311]:
df01 = df0.copy()
df01['c7'] = 'newjalmen'
print df0 
print df01

      c1  c2  c3  c4  c5  c6      c7
1000   0   1   2  20   4   5  jalmen
2000   6   7   8  25  10  11  jalmen
3000  12  13  14  15  16  17  jalmen
      c1  c2  c3  c4  c5  c6         c7
1000   0   1   2  20   4   5  newjalmen
2000   6   7   8  25  10  11  newjalmen
3000  12  13  14  15  16  17  newjalmen


In [312]:
for (name,serie) in df0.iteritems():
    print name
    print serie.index
    print serie.values

c1
Int64Index([1000, 2000, 3000], dtype='int64')
[ 0  6 12]
c2
Int64Index([1000, 2000, 3000], dtype='int64')
[ 1  7 13]
c3
Int64Index([1000, 2000, 3000], dtype='int64')
[ 2  8 14]
c4
Int64Index([1000, 2000, 3000], dtype='int64')
[20 25 15]
c5
Int64Index([1000, 2000, 3000], dtype='int64')
[ 4 10 16]
c6
Int64Index([1000, 2000, 3000], dtype='int64')
[ 5 11 17]
c7
Int64Index([1000, 2000, 3000], dtype='int64')
['jalmen' 'jalmen' 'jalmen']


In [313]:
for (name,serie) in df0.iterrows():
    print name
    print serie.index
    print serie.values

1000
Index([u'c1', u'c2', u'c3', u'c4', u'c5', u'c6', u'c7'], dtype='object')
[0 1 2 20 4 5 'jalmen']
2000
Index([u'c1', u'c2', u'c3', u'c4', u'c5', u'c6', u'c7'], dtype='object')
[6 7 8 25 10 11 'jalmen']
3000
Index([u'c1', u'c2', u'c3', u'c4', u'c5', u'c6', u'c7'], dtype='object')
[12 13 14 15 16 17 'jalmen']


#### Maths on the whole DataFrame

In [336]:
df0['c4'] = [-20,25,-15]
df0['c7'] = [-8,np.nan,4]
df0

c1  c2  c3  c4  c5  c6  c7
1000   0   1   2 -20   4   5  -8
2000   6   7   8  25  10  11 NaN
3000  12  13  14 -15  16  17   4

In [337]:
df0.abs()

c1  c2  c3  c4  c5  c6  c7
1000   0   1   2  20   4   5   8
2000   6   7   8  25  10  11 NaN
3000  12  13  14  15  16  17   4

In [338]:
df0.add(1000)

c1    c2    c3    c4    c5    c6    c7
1000  1000  1001  1002   980  1004  1005   992
2000  1006  1007  1008  1025  1010  1011   NaN
3000  1012  1013  1014   985  1016  1017  1004

In [358]:
df0.mul(6)

c1  c2  c3   c4  c5   c6  c7
1000   0   6  12 -120  24   30 -48
2000  36  42  48  150  60   66 NaN
3000  72  78  84  -90  96  102  24

In [348]:
df0.div(6)

c1        c2        c3        c4        c5        c6        c7
1000   0  0.166667  0.333333 -3.333333  0.666667  0.833333 -1.333333
2000   1  1.166667  1.333333  4.166667  1.666667  1.833333       NaN
3000   2  2.166667  2.333333 -2.500000  2.666667  2.833333  0.666667

In [340]:
df0.cummax()

c1  c2  c3  c4  c5  c6  c7
1000   0   1   2 -20   4   5  -8
2000   6   7   8  25  10  11 NaN
3000  12  13  14  25  16  17   4

In [341]:
df0.cummax(axis=1)

c1  c2  c3  c4  c5  c6  c7
1000   0   1   2   2   4   5   5
2000   6   7   8  25  25  25 NaN
3000  12  13  14  14  16  17  17

In [342]:
df0.cummin()

c1  c2  c3  c4  c5  c6  c7
1000   0   1   2 -20   4   5  -8
2000   0   1   2 -20   4   5 NaN
3000   0   1   2 -20   4   5  -8

In [343]:
df0.cumsum()

c1  c2  c3  c4  c5  c6  c7
1000   0   1   2 -20   4   5  -8
2000   6   8  10   5  14  16 NaN
3000  18  21  24 -10  30  33  -4

In [344]:
df0.cumprod()

c1  c2   c3    c4   c5   c6  c7
1000   0   1    2   -20    4    5  -8
2000   0   7   16  -500   40   55 NaN
3000   0  91  224  7500  640  935 -32

In [347]:
print df0
df0.diff()

      c1  c2  c3  c4  c5  c6  c7
1000   0   1   2 -20   4   5  -8
2000   6   7   8  25  10  11 NaN
3000  12  13  14 -15  16  17   4


c1  c2  c3  c4  c5  c6  c7
1000 NaN NaN NaN NaN NaN NaN NaN
2000   6   6   6  45   6   6 NaN
3000   6   6   6 -40   6   6 NaN

In [358]:
df0.count()

c1    4
c2    4
c3    4
c4    2
c5    2
c6    2
dtype: int64

In [355]:
df0.sum()

c1    18
c2    21
c3    24
c4   -10
c5    30
c6    33
c7    -4
dtype: float64

In [353]:
df0.max()

c1    12
c2    13
c3    14
c4    25
c5    16
c6    17
c7     4
dtype: float64

In [357]:
df0.min()

c1     0
c2     1
c3     2
c4   -20
c5     4
c6     5
c7    -8
dtype: float64

In [354]:
df0.mean()

c1     6.000000
c2     7.000000
c3     8.000000
c4    -3.333333
c5    10.000000
c6    11.000000
c7    -2.000000
dtype: float64

In [356]:
df0.median()

c1     6
c2     7
c3     8
c4   -15
c5    10
c6    11
c7    -2
dtype: float64

In [367]:
df0.filter(items=['c'+str(i) for i in range(8) if i %2 == 1],axis=1)

c1  c3  c5  c7
1000   0   2   4  -8
2000   6   8  10 NaN
3000  12  14  16   4

In [364]:
df0.filter(items=[i*1000 for i in range(1,4) if i %2 == 1], axis=0)

c1  c2  c3  c4  c5  c6  c7
1000   0   1   2 -20   4   5  -8
3000  12  13  14 -15  16  17   4

In [384]:
df0.columns=['c1','c2','d3','c4','c5','d6','c7']
df0.filter(like='d')

d3  d6
1000   2   5
2000   8  11
3000  14  17

## Working with Columns

In [25]:
df0

c1  c2  c3  c4  c5  c6
1000   0   1   2   3   4   5
2000   6   7   8   9  10  11
3000  12  13  14  15  16  17

In [11]:
df0.columns.tolist()

['c1', 'c2', 'c3', 'c4', 'c5', 'c6']

In [72]:
df0.rename(columns={'c1':'col1','c2':'col2'}, inplace=True)
df0

col1  col2  c3  c4  c5  c6
1000     0     1   2   3   4   5
2000     6     7   8   9  10  11
3000    12    13  14  15  16  17

In [30]:
df0['c3']

1000     2
2000     8
3000    14
Name: c3, dtype: int64

In [28]:
df0[['c3']]

c3
1000   2
2000   8
3000  14

In [34]:
df0[['c6','c3','c5']]

c6  c3  c5
1000   5   2   4
2000  11   8  10
3000  17  14  16

In [48]:
df0.pop('c3')
df0

col1  col2  c4  c5  c6
1000     0     1   3   4   5
2000     6     7   9  10  11
3000    12    13  15  16  17

In [40]:
df0

col1  col2  c4  c5  c6
1000     0     1   3   4   5
2000     6     7   9  10  11
3000    12    13  15  16  17

In [56]:
df0.c5

1000     4
2000    10
3000    16
Name: c5, dtype: int64

In [59]:
df0['c7']=df0.c5*df0.c6
df0

col1  col2  c4  c5  c6   c7
1000     0     1   3   4   5   20
2000     6     7   9  10  11  110
3000    12    13  15  16  17  272

In [73]:
df0['c8'] = np.random.rand(len(df0))
df0

col1  col2  c3  c4  c5  c6        c8
1000     0     1   2   3   4   5  0.216101
2000     6     7   8   9  10  11  0.259763
3000    12    13  14  15  16  17  0.566447

In [74]:
df0[['c9','c10']] = df0[['col1','col2']]
df0

col1  col2  c3  c4  c5  c6        c8  c9  c10
1000     0     1   2   3   4   5  0.216101   0    1
2000     6     7   8   9  10  11  0.259763   6    7
3000    12    13  14  15  16  17  0.566447  12   13

In [78]:
# Swapping columns
df0[['col2','col1']] = df0[['col1','col2']]
df0

col1  col2  c3  c4  c5  c6        c8  c9  c10
1000     1     0   2   3   4   5  0.216101   0    1
2000     7     6   8   9  10  11  0.259763   6    7
3000    13    12  14  15  16  17  0.566447  12   13

In [81]:
df0.pop('c4')
df0

col1  col2  c5  c6        c8  c9  c10
1000     1     0   4   5  0.216101   0    1
2000     7     6  10  11  0.259763   6    7
3000    13    12  16  17  0.566447  12   13

In [86]:
df0.drop('c8',axis=1,inplace=True)
df0

col1  col2  c5  c6  c9  c10
1000     1     0   4   5   0    1
2000     7     6  10  11   6    7
3000    13    12  16  17  12   13

In [87]:
del df0['c9']
df0

col1  col2  c5  c6  c10
1000     1     0   4   5    1
2000     7     6  10  11    7
3000    13    12  16  17   13

In [96]:
df0['c6']/df0['c10']


1000    5.000000
2000    1.571429
3000    1.307692
dtype: float64

In [97]:
df0.col1*100

1000     100
2000     700
3000    1300
Name: col1, dtype: int64

In [98]:
np.round(df0['c6']/df0['c10'])

1000    5
2000    2
3000    1
dtype: float64

In [103]:
# Columns set by criteria
df0['c12'] = df0['c5'].where(df0['c5'] % 5 == 0, other=df0['col1'])
df0

col1  col2  c5  c6  c10  c12
1000     1     0   4   5    1    1
2000     7     6  10  11    7   10
3000    13    12  16  17   13   13

In [107]:
df0['c12'].astype(str).tolist()

['1', '10', '13']

In [371]:
print df0['col1'].dtype
print df0['col1'].size
print df0['col1'].count()
print df0['col1'].sum()
print df0['col1'].prod()
print df0['col1'].min()
print df0['col1'].max()
print df0['col1'].mean()
print df0['col1'].median()

int64
4
4
36
0
0
18
9.0
9.0


In [121]:
print df0['col1'].value_counts()

7     1
13    1
1     1
dtype: int64


In [129]:
df0['c14']=[36,50,12]
print df0
print
print df0['c14'].idxmin()
print df0['c14'].idxmax()

      col1  col2  c5  c6  c10  c12  c14
1000     1     0   4   5    1    1   36
2000     7     6  10  11    7   10   50
3000    13    12  16  17   13   13   12

3000
2000


In [152]:
df0['c15']=[360.5,np.nan,120]
print df0['c15'].isnull()
print
print df0['c15'].notnull()
print
print df0['c15'].round()
print
df0['c15'] = df0['c15'].fillna(240)
print df0
print
print df0['c15'].cumsum()
print
print df0['c15'].cumprod()
print
print df0['c15'].pct_change()

1000    False
2000     True
3000    False
Name: c15, dtype: bool

1000     True
2000    False
3000     True
Name: c15, dtype: bool

1000    360
2000    NaN
3000    120
Name: c15, dtype: float64

      c1  c2  c3  c4  c5  c6    c15
1000   0   1   2   3   4   5  360.5
2000   6   7   8   9  10  11  240.0
3000  12  13  14  15  16  17  120.0

1000    360.5
2000    600.5
3000    720.5
Name: c15, dtype: float64

1000         360.5
2000       86520.0
3000    10382400.0
Name: c15, dtype: float64

1000         NaN
2000   -0.334258
3000   -0.500000
Name: c15, dtype: float64


In [159]:
df0['c16']=df0.sum(axis=1)
df0

c1  c2  c3  c4  c5  c6    c15    c16
1000   0   1   2   3   4   5  360.5  375.5
2000   6   7   8   9  10  11  240.0  291.0
3000  12  13  14  15  16  17  120.0  207.0

In [165]:
print df0.mul([3,2,1], axis=0)
print
print df0.mul([8,7,6,5,4,3,2,1], axis=1)

      c1  c2  c3  c4  c5  c6     c15     c16
1000   0   3   6   9  12  15  1081.5  1126.5
2000  12  14  16  18  20  22   480.0   582.0
3000  12  13  14  15  16  17   120.0   207.0

      c1  c2  c3  c4  c5  c6  c15    c16
1000   0   7  12  15  16  15  721  375.5
2000  48  49  48  45  40  33  480  291.0
3000  96  91  84  75  64  51  240  207.0


In [172]:
print df0.columns.get_loc('c4')
print df0.columns.is_unique

3
True


## Working with rows

In [246]:
df0 = DataFrame(np.array([range(6),range(6,12),range(12,18),range(18,24)]))
df0.index=[1000,2000,3000,4000]
df0.columns=['c1','c2','c3','c4','c5','c6']
df0

c1  c2  c3  c4  c5  c6
1000   0   1   2   3   4   5
2000   6   7   8   9  10  11
3000  12  13  14  15  16  17
4000  18  19  20  21  22  23

In [15]:
df0.index.tolist()

[1000, 2000, 3000]

In [20]:
df0.index = np.round(np.random.rand(len(df0))*100)
df0

c1  c2  c3  c4  c5  c6
24   0   1   2   3   4   5
2    6   7   8   9  10  11
15  12  13  14  15  16  17

In [22]:
# It does not modify DataFrame
df0.reset_index()

index  c1  c2  c3  c4  c5  c6
0     24   0   1   2   3   4   5
1      2   6   7   8   9  10  11
2     15  12  13  14  15  16  17

In [56]:
df0.reindex(index=range(len(df0)))

c1  c2  c3  c4  c5  c6
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2   6   7   8   9  10  11

In [61]:
df0.rename(index={24:'i0'})

c1  c2  c3  c4  c5  c6
24   0   1   2   3   4   5
2    6   7   8   9  10  11
15  12  13  14  15  16  17

In [75]:
# It does not modify DataFrame
df0.drop(2)

c1  c2  c3  c4  c5  c6
24   0   1   2   3   4   5
15  12  13  14  15  16  17

In [85]:
df0[(df0['c2'] >= 7) & (df0['c4'] < 15)]

c1  c2  c3  c4  c5  c6
2   6   7   8   9  10  11

In [93]:
df0[df0['c2'].isin([1,3,7])]

c1  c2  c3  c4  c5  c6
24   0   1   2   3   4   5
2    6   7   8   9  10  11

In [95]:
df0['c7'] = ['Save','the','Pandas']
df0

c1  c2  c3  c4  c5  c6      c7
24   0   1   2   3   4   5    Save
2    6   7   8   9  10  11     the
15  12  13  14  15  16  17  Pandas

In [97]:
df0[df0['c7'].str.contains('and')]

c1  c2  c3  c4  c5  c6      c7
15  12  13  14  15  16  17  Pandas

In [129]:
df0 = df0.reset_index()
del df0['index']
df0

c1  c2  c3  c4  c5  c6      c7
0   0   1   2   3   4   5    Save
1   6   7   8   9  10  11     the
2  12  13  14  15  16  17  Pandas

In [225]:
df0 = DataFrame(np.array([range(12,18),range(6,12),range(18,24),range(6)]))
df0.index=[1000,2000,3000,4000]
df0.columns=['c1','c2','c3','c4','c5','c6']
df0

c1  c2  c3  c4  c5  c6
1000  12  13  14  15  16  17
2000   6   7   8   9  10  11
3000  18  19  20  21  22  23
4000   0   1   2   3   4   5

In [226]:
df0.ix[2000:3000]

c1  c2  c3  c4  c5  c6
2000   6   7   8   9  10  11
3000  18  19  20  21  22  23

In [227]:
df0.ix[2000:]

c1  c2  c3  c4  c5  c6
2000   6   7   8   9  10  11
3000  18  19  20  21  22  23
4000   0   1   2   3   4   5

In [228]:
df0 = df0.reset_index()
df0

index  c1  c2  c3  c4  c5  c6
0   1000  12  13  14  15  16  17
1   2000   6   7   8   9  10  11
2   3000  18  19  20  21  22  23
3   4000   0   1   2   3   4   5

In [229]:
df0[1::2]

index  c1  c2  c3  c4  c5  c6
1   2000   6   7   8   9  10  11
3   4000   0   1   2   3   4   5

In [230]:
df0.append(DataFrame({col:df0[col].sum() for col in df0.columns},index=['Total']))

c1  c2  c3  c4  c5  c6  index
0      12  13  14  15  16  17   1000
1       6   7   8   9  10  11   2000
2      18  19  20  21  22  23   3000
3       0   1   2   3   4   5   4000
Total  36  40  44  48  52  56  10000

In [236]:
# Inplace modifies Dataframe
df0.sort('c5',inplace=True)
df0

index  c1  c2  c3  c4  c5  c6
3   4000   0   1   2   3   4   5
1   2000   6   7   8   9  10  11
0   1000  12  13  14  15  16  17
2   3000  18  19  20  21  22  23

In [245]:
df0.index=df0['index'].values.tolist()
del df0['index']
df0

c1  c2  c3  c4  c5  c6
4000   0   1   2   3   4   5
2000   6   7   8   9  10  11
1000  12  13  14  15  16  17
3000  18  19  20  21  22  23

## Working with cells

In [251]:
print df0.at[2000,'c2']
print df0.loc[2000,'c2']
print df0['c2'].at[2000]

7
7
7


In [253]:
df0.at[2000,'c2'] = 888
df0.loc[2000,'c3'] = 999
df0['c4'].at[2000] = 777
df0

c1   c2   c3   c4  c5  c6
1000   0    1    2    3   4   5
2000   6  888  999  777  10  11
3000  12   13   14   15  16  17
4000  18   19   20   21  22  23

In [257]:
df0.loc[2000:3000,'c4':'c6']

c4  c5  c6
2000  777  10  11
3000   15  16  17

In [260]:
df0.loc[2000:3000,'c4':'c6'] = np.nan
df0

c1   c2   c3  c4  c5  c6
1000   0    1    2   3   4   5
2000   6  888  999 NaN NaN NaN
3000  12   13   14 NaN NaN NaN
4000  18   19   20  21  22  23

In [352]:
df0[['c'+str(i) for i in range(3,7)]]

c3  c4  c5  c6
1000    2   3   4   5
2000  999 NaN NaN NaN
3000   14 NaN NaN NaN
4000   20  21  22  23

In [333]:
df0[df0['c3'] > 500]

c1   c2   c3  c4  c5  c6
2000   6  888  999 NaN NaN NaN

In [350]:
df0.loc[2000:3000]

c1   c2   c3  c4  c5  c6
2000   6  888  999 NaN NaN NaN
3000  12   13   14 NaN NaN NaN

In [355]:
df0.loc[2000:3000,'c3':'c5']

c3  c4  c5
2000  999 NaN NaN
3000   14 NaN NaN

## Groupby

In [395]:
df0 = DataFrame(np.array([range(12,18),range(6,12),range(12,18),range(6)]))
df0.index=[1000,2000,3000,4000]
df0.columns=['c1','c2','c3','c4','c5','c6']
df0.loc[2000,'c2']=13
df0

c1  c2  c3  c4  c5  c6
1000  12  13  14  15  16  17
2000   6  13   8   9  10  11
3000  12  13  14  15  16  17
4000   0   1   2   3   4   5

In [408]:
gb0 = df0.groupby('c2')
for name,group in gb0:
    print name, group['c4'].mean()

1 3.0
13 13.0


In [410]:
gb0.get_group(13)

c1  c2  c3  c4  c5  c6
1000  12  13  14  15  16  17
2000   6  13   8   9  10  11
3000  12  13  14  15  16  17

In [413]:
gb0.get_group(13)['c4'].sum()

39

In [423]:
gb0.get_group(13)

c1  c2  c3  c4  c5  c6
1000  12  13  14  15  16  17
2000   6  13   8   9  10  11
3000  12  13  14  15  16  17