In [4]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
%matplotlib inline

### Dataframes

In [5]:
df1 = DataFrame([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]],columns=['c1','c2','c3','c4','c5'])
df1

c1  c2  c3  c4  c5
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [6]:
df1 = DataFrame({'c1':[0,5,10],'c2':[1,6,11],'c3':[2,7,12],'c4':[3,8,13],'c5':[4,9,14]})
df1

c1  c2  c3  c4  c5
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [7]:
df1 = DataFrame(np.arange(15).reshape(3,5), columns=['c'+str(i) for i in range(1,6)])
df1

c1  c2  c3  c4  c5
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [8]:
print df1.columns
print 
print df1.index
print 
print df1.values

Index([u'c1', u'c2', u'c3', u'c4', u'c5'], dtype='object')

Int64Index([0, 1, 2], dtype='int64')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
print df1['c4']
print
print df1[df1.columns[2:4]]
print
print df1.ix[1]
print
print df1[[True,True,False]]
print
print df1[df1['c4'] % 2 == 0]

0     3
1     8
2    13
Name: c4, dtype: int64

   c3  c4
0   2   3
1   7   8
2  12  13

c1    5
c2    6
c3    7
c4    8
c5    9
Name: 1, dtype: int64

   c1  c2  c3  c4  c5
0   0   1   2   3   4
1   5   6   7   8   9

   c1  c2  c3  c4  c5
1   5   6   7   8   9


In [10]:
# Appending columns
df1['c6'] = [10,20,30]
df1['c7'] = df1['c6']*10
df1['c8'] = df1['c6']+df1['c7']
df1

c1  c2  c3  c4  c5  c6   c7   c8
0   0   1   2   3   4  10  100  110
1   5   6   7   8   9  20  200  220
2  10  11  12  13  14  30  300  330

In [11]:
# Appending rows (it does not modify DataFrame)
df1 = df1.append(df1.ix[2]*10, ignore_index=True)
df1 = df1.append(df1.ix[2]+df1.ix[3], ignore_index=True)
df1

c1   c2   c3   c4   c5   c6    c7    c8
0    0    1    2    3    4   10   100   110
1    5    6    7    8    9   20   200   220
2   10   11   12   13   14   30   300   330
3  100  110  120  130  140  300  3000  3300
4  110  121  132  143  154  330  3300  3630

### Functions

In [12]:
# applymap and apply do not modify Dataframe
def sumten(n):
    return n+10
df1.applymap(sumten)

c1   c2   c3   c4   c5   c6    c7    c8
0   10   11   12   13   14   20   110   120
1   15   16   17   18   19   30   210   230
2   20   21   22   23   24   40   310   340
3  110  120  130  140  150  310  3010  3310
4  120  131  142  153  164  340  3310  3640

In [13]:
def meanserie(s):
    return s.mean()
print df1.apply(meanserie)
print
print df1.apply(lambda s: s.mean())

c1      45.0
c2      49.8
c3      54.6
c4      59.4
c5      64.2
c6     138.0
c7    1380.0
c8    1518.0
dtype: float64

c1      45.0
c2      49.8
c3      54.6
c4      59.4
c5      64.2
c6     138.0
c7    1380.0
c8    1518.0
dtype: float64


### Merging

In [32]:
df1 = DataFrame(np.random.randint(0,10,3*5).reshape(3,5))
df1.columns = ['c1','c2','c3','c4','c5']
df1['key1'] = ['a','a','b']
df1

c1  c2  c3  c4  c5 key1
0   3   9   5   8   6    a
1   9   3   6   6   6    a
2   4   7   2   6   5    b

In [48]:
df2 = DataFrame(np.random.randint(0,10,3*5).reshape(3,5))
df2.columns = ['c1','c2','c3','c4','c5']
df2['key1'] = ['b','a','c']
df2['key2'] = df2['key1']
df2

c1  c2  c3  c4  c5 key1 key2
0   1   7   7   5   1    b    b
1   1   7   0   0   3    a    a
2   3   5   7   8   6    c    c

In [49]:
pd.merge(df1,df2,on='key1')

c1_x  c2_x  c3_x  c4_x  c5_x key1  c1_y  c2_y  c3_y  c4_y  c5_y key2
0     3     9     5     8     6    a     1     7     0     0     3    a
1     9     3     6     6     6    a     1     7     0     0     3    a
2     4     7     2     6     5    b     1     7     7     5     1    b

In [50]:
pd.merge(df1,df2,on='key1',how='inner')

c1_x  c2_x  c3_x  c4_x  c5_x key1  c1_y  c2_y  c3_y  c4_y  c5_y key2
0     3     9     5     8     6    a     1     7     0     0     3    a
1     9     3     6     6     6    a     1     7     0     0     3    a
2     4     7     2     6     5    b     1     7     7     5     1    b

In [51]:
pd.merge(df1,df2,on='key1',how='outer')

c1_x  c2_x  c3_x  c4_x  c5_x key1  c1_y  c2_y  c3_y  c4_y  c5_y key2
0     3     9     5     8     6    a     1     7     0     0     3    a
1     9     3     6     6     6    a     1     7     0     0     3    a
2     4     7     2     6     5    b     1     7     7     5     1    b
3   NaN   NaN   NaN   NaN   NaN    c     3     5     7     8     6    c

In [57]:
pd.merge(df1,df2,left_on='key1',right_on='key2',how='inner')

c1_x  c2_x  c3_x  c4_x  c5_x key1_x  c1_y  c2_y  c3_y  c4_y  c5_y key1_y  \
0     3     9     5     8     6      a     1     7     0     0     3      a   
1     9     3     6     6     6      a     1     7     0     0     3      a   
2     4     7     2     6     5      b     1     7     7     5     1      b   

  key2  
0    a  
1    a  
2    b

In [58]:
pd.merge(df1,df2,left_on='key1',right_on='key2',how='outer')

c1_x  c2_x  c3_x  c4_x  c5_x key1_x  c1_y  c2_y  c3_y  c4_y  c5_y key1_y  \
0     3     9     5     8     6      a     1     7     0     0     3      a   
1     9     3     6     6     6      a     1     7     0     0     3      a   
2     4     7     2     6     5      b     1     7     7     5     1      b   
3   NaN   NaN   NaN   NaN   NaN    NaN     3     5     7     8     6      c   

  key2  
0    a  
1    a  
2    b  
3    c

In [59]:
## Grouping

In [60]:
!ls -l

total 207468
-rw-rw-r--. 1 dsc vboxsf    311761 Dec 18 21:52 grouping.ipynb
-rw-rw-r--. 1 dsc dsc       242020 Dec 19 13:21 load_and_examples.ipynb
-rw-r--r--. 1 dsc vboxsf 211633432 Apr 16  2015 On_Time_On_Time_Performance_2015_1.csv
-rw-r--r--. 1 dsc vboxsf     12054 Apr 16  2015 readme.html
-rw-rw-r--. 1 dsc vboxsf     27904 Dec 18 21:52 reviewing_pandas.ipynb
-rw-r--r--. 1 dsc vboxsf    156502 Dec 29 12:22 studying_cheat_sheet_pandas_dataframe.ipynb
-rw-r--r--. 1 dsc vboxsf     45614 Dec 29 19:28 studying_python_and_pandas_03.ipynb


In [61]:
df1 = pd.read_csv('On_Time_On_Time_Performance_2015_1.csv', low_memory=False)

In [62]:
df1.sample()

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
310016  2015        1      1          15          4  2015-01-15            UA   

        AirlineID Carrier TailNum      ...       Div4TailNum  Div5Airport  \
310016      19977      UA  N37471      ...               NaN          NaN   

        Div5AirportID  Div5AirportSeqID Div5WheelsOn Div5TotalGTime  \
310016            NaN               NaN          NaN            NaN   

       Div5LongestGTime  Div5WheelsOff Div5TailNum  Unnamed: 109  
310016              NaN            NaN         NaN           NaN  

[1 rows x 110 columns]

In [63]:
df1[(df1['Year'] == 2015) & (df1['Month'] == 1) & (df1['DayofMonth'] == 22)].sample()

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
467455  2015        1      1          22          4  2015-01-22            MQ   

        AirlineID Carrier TailNum      ...       Div4TailNum  Div5Airport  \
467455      20398      MQ  N601MQ      ...               NaN          NaN   

        Div5AirportID  Div5AirportSeqID Div5WheelsOn Div5TotalGTime  \
467455            NaN               NaN          NaN            NaN   

       Div5LongestGTime  Div5WheelsOff Div5TailNum  Unnamed: 109  
467455              NaN            NaN         NaN           NaN  

[1 rows x 110 columns]

In [64]:
df1.dtypes

Year                    int64
Quarter                 int64
Month                   int64
DayofMonth              int64
DayOfWeek               int64
FlightDate             object
UniqueCarrier          object
AirlineID               int64
Carrier                object
TailNum                object
FlightNum               int64
OriginAirportID         int64
OriginAirportSeqID      int64
OriginCityMarketID      int64
Origin                 object
OriginCityName         object
OriginState            object
OriginStateFips         int64
OriginStateName        object
OriginWac               int64
DestAirportID           int64
DestAirportSeqID        int64
DestCityMarketID        int64
Dest                   object
DestCityName           object
DestState              object
DestStateFips           int64
DestStateName          object
DestWac                 int64
CRSDepTime              int64
                       ...   
Div2WheelsOn          float64
Div2TotalGTime        float64
Div2Longes

In [65]:
len(df1)

469968

In [66]:
minidf1 = df1[df1['FlightDate'] == "2015-01-22"]
len(minidf1)

16013

In [67]:
by_carrier = minidf1.groupby('Carrier')

In [93]:
by_carrier.get_group('AS').sample(5)

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
50029  2015        1      1          22          4  2015-01-22            AS   
50384  2015        1      1          22          4  2015-01-22            AS   
50126  2015        1      1          22          4  2015-01-22            AS   
50296  2015        1      1          22          4  2015-01-22            AS   
50310  2015        1      1          22          4  2015-01-22            AS   

       AirlineID Carrier TailNum      ...       Div4TailNum  Div5Airport  \
50029      19930      AS  N556AS      ...               NaN          NaN   
50384      19930      AS  N527AS      ...               NaN          NaN   
50126      19930      AS  N531AS      ...               NaN          NaN   
50296      19930      AS  N408AS      ...               NaN          NaN   
50310      19930      AS  N402AS      ...               NaN          NaN   

       Div5AirportID  Div5AirportSeqID Div5WheelsOn Div5TotalGTime  \
50029            NaN               NaN          NaN            NaN   
50384            NaN               NaN          NaN            NaN   
50126            NaN               NaN          NaN            NaN   
50296            NaN               NaN          NaN            NaN   
50310            NaN               NaN          NaN            NaN   

      Div5LongestGTime  Div5WheelsOff Div5TailNum  Unnamed: 109  
50029              NaN            NaN         NaN           NaN  
50384              NaN            NaN         NaN           NaN  
50126              NaN            NaN         NaN           NaN  
50296              NaN            NaN         NaN           NaN  
50310              NaN            NaN         NaN           NaN  

[5 rows x 110 columns]

In [140]:
by_carrierandorigin = minidf1.groupby(['Carrier','Origin'])
by_carrierandorigin.get_group(('UA', 'LAS')).sample(5)

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate UniqueCarrier  \
304785  2015        1      1          22          4  2015-01-22            UA   
299444  2015        1      1          22          4  2015-01-22            UA   
302943  2015        1      1          22          4  2015-01-22            UA   
299289  2015        1      1          22          4  2015-01-22            UA   
304635  2015        1      1          22          4  2015-01-22            UA   

        AirlineID Carrier TailNum      ...       Div4TailNum  Div5Airport  \
304785      19977      UA  N77530      ...               NaN          NaN   
299444      19977      UA  N847UA      ...               NaN          NaN   
302943      19977      UA  N77258      ...               NaN          NaN   
299289      19977      UA  N805UA      ...               NaN          NaN   
304635      19977      UA  N803UA      ...               NaN          NaN   

        Div5AirportID  Div5AirportSeqID Div5WheelsOn Div5TotalGTime  \
304785            NaN               NaN          NaN            NaN   
299444            NaN               NaN          NaN            NaN   
302943            NaN               NaN          NaN            NaN   
299289            NaN               NaN          NaN            NaN   
304635            NaN               NaN          NaN            NaN   

       Div5LongestGTime  Div5WheelsOff Div5TailNum  Unnamed: 109  
304785              NaN            NaN         NaN           NaN  
299444              NaN            NaN         NaN           NaN  
302943              NaN            NaN         NaN           NaN  
299289              NaN            NaN         NaN           NaN  
304635              NaN            NaN         NaN           NaN  

[5 rows x 110 columns]

In [153]:
for i,dataframe in by_carrier:
    print i, "\t", len(dataframe)

AA 	1443
AS 	436
B6 	710
DL 	2304
EV 	1728
F9 	223
HA 	208
MQ 	1009
NK 	281
OO 	1616
UA 	1345
US 	1171
VX 	163
WN 	3376


In [155]:
by_carrier['Year'].count()

Carrier
AA    1443
AS     436
B6     710
DL    2304
EV    1728
F9     223
HA     208
MQ    1009
NK     281
OO    1616
UA    1345
US    1171
VX     163
WN    3376
Name: Year, dtype: int64

In [157]:
by_carrier.apply(lambda s: len(s))

Carrier
AA    1443
AS     436
B6     710
DL    2304
EV    1728
F9     223
HA     208
MQ    1009
NK     281
OO    1616
UA    1345
US    1171
VX     163
WN    3376
dtype: int64